### ISSUE TITLE
Random number (or letter) generation for file name format 

### ISSUE THREAD

**Issue by Sunako** [olav-st/screencloud#10]
I'm not quite sure if the full options for file names are listed anywhere, nowhere I saw anyway, but the topic suggestion is in the interest of privacy for private hosted images. For me I usually use the yyMMddhhmmss format, making guessing a file name not all that easy for some just curious. However if someone were more interested they could easily just setup a small script to try and GET request ever increasing seconds, minutes, hours, days, etc and collect all your future (and past if they cared to do that) images. I propose some random generation option for the file naming format.

As an example of my above idea I'd use something like yyMMddhhmmss_rnd would end up 131018032250_5 for one and 131018032250_9 for the next one, that example would only happen if you somehow took two screenshots at the same second, not very likely. Making the option "stack" would be good too. For example just one"rnd" in the format produces one random number, or letter if you want, to add wherever the users puts it, but if you did "rndrnd" it would produce two, and so on.

Now obviously all this isn't needed if you are just careful not to take a screenshot of anything you wouldn't want found, or to just make sure to delete it. But sadly we are prone to forgetting things. If anything above was unclear or requires more detail I'm happy to oblige to try and fix it.

**Comment by thispixel** [comment]
Just a quick update on this looking at the source code using {rnd_s} is what you guys are after.

**Comment by celebrir** [comment]
@thispixel You're my hero!
❤❤❤❤❤❤❤❤❤❤

**Comment by ilyahoilik** [comment]
Any progress?

**Comment by gentoo-cba** [comment]
if you just want short links I used %s 
Number of seconds since the UNIX epoch - works with python on Linux.
