### ISSUE TITLE
Screenshots taken with computer date changed block future screenshots 

### ISSUE THREAD

**Issue by nathannfm** [olav-st/screencloud#102]
I took a screenshot of my computer clock after setting it to a date in the future and now that I have set it back to the current time I can no longer upload screenshots due to a timestamp error. 
![capture](https://cloud.githubusercontent.com/assets/1588961/4588520/05b90926-5045-11e4-8d9d-64df0603fc11.PNG)

I suggest using your server time to stamp them to avoid this.

It seems my account is now useless until the time I set it to actually passes.

**Comment by olav-st** [comment]
Closing this since the screenshot hosting service has been shut down.
