### ISSUE TITLE
.gif capture

### ISSUE THREAD

**Issue by BoomLiam** [olav-st/screencloud#112]
Firstly, I setup ScreenCloud to upload to my own FTP server, it's something that I am now using to replace Gyazo as, initially, it seems far more stable! I have only been using it a little while, but I must thank you, this application is amazing!

I'm sure you've considered this request before, but I just wanted to let let you know that a .gif capture feature would be AMAZING in ScreenCloud, and that there is a demand for it. I hope you will consider implementing it and I really look forward to what can be produced. Keep up the fascinating work!

**Comment by PocketMines** [comment]
+1 That would be great!

**Comment by T-Grave** [comment]
+1 yes please

**Comment by FatBoyXPC** [comment]
Bump! This would be **AMAZING**!
