### ISSUE TITLE
Ability to create unique URLs with SFTP backend.

### ISSUE THREAD

**Issue by ninja-** [olav-st/screencloud#113]
Hi. Currently the only way to host multiple screenshots with SFTP backend is to set the name syntax like:
screenshot-%H-%M-%S.png

which will make an URL with date.
However there are a few problems with that:
1) A little security vulnerability when you could "brute-force" and watch screenshots you were not linked to
2) Older screenshots could get overriden(well maybe not that much if you add more date stuff into the link....)

So the proposed solution/change is to create a syntax which will allow to inject some randomess into the URL, preferably with a configurable length like...
%RANDOM:10% which would generate a random string using safe chars

Alternatively, long random UUIDs could be used.

Thanks!

**Comment by msound** [comment]
Since pull request #118 was merged, it is now possible to use `{rnd_s}` to get a short 8 character filename. This issue can be marked as closed.
