### ISSUE TITLE
Black image in VirtualBox

### ISSUE THREAD

**Issue by edakhmetgareev** [olav-st/screencloud#116]
Hello, 

I have Linux Mint 17 run on VirtualBox under Windows 8.1

When I try make screenshot, it takes only black screen, like this http://screencloud.net/v/loGC 

I have one display.

**Comment by JoshMcCullough** [comment]
Same issue here. Some information in [this post](https://www.virtualbox.org/ticket/11758) suggest that it was fixed a year ago. Note that I have 3D Acceleration enabled but when I disable it, screenshots work correctly.
