### ISSUE TITLE
FTP uploading issue

### ISSUE THREAD

**Issue by Stannaz** [olav-st/screencloud#117]
I was planning to use ScreenCloud on all of my machines (2 Windows, 1 Ubuntu Linux), and started by installing the software on my Ubuntu computer, installation was successful and everything appeared okay. I proceeded to configure the FTP credentials I had designated for ScreenCloud, but when I went to test it by uploading a screenshot, it just sat and did nothing with the up arrow on the panel icon, so I left it. After around 2 minutes, an error window popped up ( http://i.imgur.com/1gIXp99.png ) and on the FTP log, there wasn't any signs of any attempt of a connection. Since I own the Windows server hosting the FTP server, I thought I'd install the Windows version of the software on it, and see if it will work when trying to connect to localhost, this also failed with the same error ( http://i.imgur.com/tetg7Aq.png ).

I would like to point out that my FTP server setup is different as it is hosted on a different port other than 21.

Thanks.

EDIT: I believe I've found the issue. The program always tries to connect on port 21, regardless of what the user set (this explains why my server running on a non-standard port failed to receive a connection).

In https://github.com/olav-st/screencloud-plugins/blob/master/ftp/main.py on line 69

ftp = ftplib.FTP(self.host)

needs replacing with

ftp = ftplib.FTP(self.host, self.port)

**Comment by olav-st** [comment]
Thanks for the heads up! Should be fixed by https://github.com/olav-st/screencloud-plugins/commit/c8c00a3e8011ae2c55c435bc299c1f1d966b64c1.
