### ISSUE TITLE
qt5 port please

### ISSUE THREAD

**Issue by anexation** [olav-st/screencloud#119]
any time frame on a qt5 port? all dependencies are available on arch aur.. Just find this program really useful and i maintain manjaro kde plasma 5 iso and there's starting to be real issues. half the time it cant find the systray on boot, uploads fail, or lag the system during upload of pics to imgur. the failure to find the system tray on boot tells me to install sni-qt, but i was the one who personally requested sni-qt and the qt4 patch to be adopted in use on arch..

I really want to included this in the iso but with the inconsistencies i mentioned above with a qt4 only build option i am not able too.
https://forum.manjaro.org/index.php?topic=18150.0

**Comment by olav-st** [comment]
I've started working on a qt5 port in this branch: https://github.com/olav-st/screencloud/tree/qt5-port
It dosen't compile yet due to some problems with PythonQt so any help would be appriciated! :)

**Comment by Alexx-G** [comment]
Any progress on this?
I can't use screencloud on Debian Jessie + KDE. System tray isn't available (but I've installed sni-qt and sni-qt:i386) and shortcuts don't work.

**Comment by olav-st** [comment]
Not working on it at the moment

**Comment by olav-st** [comment]
@anexation Just updated the qt5-port branch. It compiles now, but a few things don't work, including global shortcuts and proper plugin support.

**Comment by olav-st** [comment]
The plugin and shortcut issues have been fixed!

**Comment by olav-st** [comment]
The Qt5 port has now been merged! See https://github.com/olav-st/screencloud/commit/5dcc325e879e5a48b2dd706fe8cd341d446e327c.
