### ISSUE TITLE
Account activation gives an SQL error

### ISSUE THREAD

**Issue by rfcdejong** [olav-st/screencloud#123]
After clicking the activation link:

Ooops, error. Code: 42000

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'GROUP BY `Ticket`.`id`' at line 1

**Comment by olav-st** [comment]
Thanks for letting me know! I've (hopefully) fixed it now.
You can resend the activation email here if you need to: http://screencloud.net/users/resend_activation

**Comment by rfcdejong** [comment]
I was able to register, thank you for fixing it this fast
