### ISSUE TITLE
Google Drive support

### ISSUE THREAD

**Issue by ElijahLynn** [olav-st/screencloud#124]
Would be nice to see support for Google Drive.

**Comment by olav-st** [comment]
This is now available: https://github.com/olav-st/screencloud-googledrive/

**Comment by cantalupo555** [comment]
How do I use this module?

**Comment by olav-st** [comment]
I have added it to the plugin list, so you should be able to install it by going to `Preferences`->`Online Services`->`More services...` 🙂
