### ISSUE TITLE
Linux: update message is redundant 

### ISSUE THREAD

**Issue by Beanow** [olav-st/screencloud#127]
![](http://ss.oscp.info/2015-02-17_08-16-34.png)
_Finding this pop-up on boot is very much a windows-like experience._

It should be possible to disable this update message in favour of letting `apt` and your dedicated update manager notify you instead. Preferably by default when installed from [a repository](http://software.opensuse.org/download.html?project=home%3Aolav-st&package=screencloud) instead of a .deb file download.

**Comment by Thor77** [comment]
It is already possible: Preferences -> Updates -> "Check for updates automatically"

**Comment by Beanow** [comment]
So I've found now on a different distro. Next problem: opening this dialogue at all on mint. Because the tray icon is not present and I've found no commandline way of opening any of the settings.

**Comment by Thor77** [comment]
wich desktop environment do you use on mint?  
are any other traybar-icons present in your bar?

**Comment by Beanow** [comment]
Cinnamon, which means only the javascript icons show up. Normally I would try opening the application again from cli, but that jusy gives me the error it's already running. If that would focus the settings instead that would solve my issue.

Thor77 <notifications@github.com> schreef op 1 maart 2015 17:47:32 CET:

**Comment by Thor77** [comment]
Im using Cinnamon on ArchLinux without any problems, i can see all traybar-icons from all applications, maybe you're missing some packages for traybar-icons to work?

**Comment by Beanow** [comment]
Amazing. The tray icons applet was just removed. And screencloud is the only thing I would use in there. Much d'oh. Thanks for your help. I'll close the issue now.
