### ISSUE TITLE
Failed call ftp.uploadto

### ISSUE THREAD

**Issue by w7rus** [olav-st/screencloud#129]
![unnamed](https://cloud.githubusercontent.com/assets/11144322/6318122/99359844-baa9-11e4-8f69-805204030727.png)

**Comment by BoomLiam** [comment]
Is your ScreenCloud updated to the latest version? (Preferences -> Updates -> "Check for updates now...")

**Comment by w7rus** [comment]
Latest 1.2.0

**Comment by olav-st** [comment]
Looks like you're connecting to the wrong port?
