### ISSUE TITLE
Rectangle option to censor images

### ISSUE THREAD

**Issue by Nothing4You** [olav-st/screencloud#130]
Hey there,
it'd be awesome if I could put e.g. black rectangles over parts of the image, just like the current rectangles, with them being filled.
Another option could also be to remove parts of the image (make them transparent, for png at least).

**Comment by wolandtel** [comment]
+1

**Comment by Nothing4You** [comment]
9 years have passed and I don't use screencloud anymore.

**Comment by olav-st** [comment]
This was actually implemented 9 years ago, see https://github.com/olav-st/screencloud/issues/5#issuecomment-74420723
