### ISSUE TITLE
Sound broken in latest update

### ISSUE THREAD

**Issue by soja92** [olav-st/screencloud#131]
The sounds for taking a screenshot, and upload complete seem to not be playing for me after the latest update.

**Comment by Nothing4You** [comment]
I can confirm this on win8.1 x64.

**Comment by soja92** [comment]
Yes sorry, forgot to include my OS version, Windows 8.1 x64 as well.

**Comment by gamemann** [comment]
Confirmed on Windows 7 64-bit.

Thanks.

**Comment by djstrikes3** [comment]
Having the same problem here as well. Windows 8.1 x64

**Comment by Thor77** [comment]
Can confirm on ArchLinux:
```
[INFO] "Uploading screenshot to 'lutim'. Size: 67164 bytes" 
[WARN] "Error while playing audio. Code: 3" 
[INFO] "URL: ..." 
[WARN] "Error while playing audio. Code: 3" 
```

**Comment by llybin** [comment]
Sound works for me, but, yes, I see this warning: [WARN] "Error while playing audio. Code: 3". ArchLinux

**Comment by olav-st** [comment]
Code 3 seems to be a buffer underrun error (see http://qt-project.org/doc/qt-4.8/qaudio.html#Error-enum)
Not sure why though, I have working audio on my arch system.

**Comment by Bubka3** [comment]
Also having this problem, Windows 8.1 x64.

**Comment by TitanicFreak** [comment]
Also having a similar issue.

**Comment by mikelvonbianchi** [comment]
Having the same issue on OSX 10.10.3

**Comment by Zeluboba** [comment]
@olav-st any possible fix? it's 11 monts old. For me, that happened first time few months ago.
