### ISSUE TITLE
Screencloud constantly uses ~5% CPU (Ubuntu 14.10)

### ISSUE THREAD

**Issue by beniwohli** [olav-st/screencloud#136]
Using Ubuntu 14.10, I'm seeing screencloud constantly using 4-5% CPU, despite me not having used it for hours. It sits at 0% until I take the first screenshot, but then never goes below 4% again until I kill it.

**Comment by deanperry** [comment]
This is off topic but how did you manage to install Screencloud on Ubuntu 14.10?

**Comment by piquadrat** [comment]
@deanperry I just installed the .deb from https://screencloud.net/#download

**Comment by piquadrat** [comment]
I just tested it on Mac OSX 10.10, the problem is not present there

**Comment by jdsampayo** [comment]
I have Xubuntu 15:04 and it uses always aroung 4% - 5%

Here a shot:
http://screencloud.net/v/42c1
