### ISSUE TITLE
Wayland support

### ISSUE THREAD

**Issue by jhass** [olav-st/screencloud#137]
I'm not sure this is feasible, since as I understood it it would require support and integration by each compositor. Though given Gnome 3.16 provides a daily usable Wayland experience, I wanted to ask.

Did you consider investigating Wayland and XWayland support so far?

**Comment by olav-st** [comment]
I have started looking at porting ScreenCloud to Qt5 (see this branch https://github.com/olav-st/screencloud/tree/qt5-port) which should make supporting wayland quite easy.

**Comment by olav-st** [comment]
The Qt 5 port has been merged (see https://github.com/olav-st/screencloud/issues/119), this should make wayland support easier.

**Comment by mcg** [comment]
Any chance Wayland is supported now?

**Comment by askl56** [comment]
Still no support here:

`Linux arch 4.10.13-1-ARCH #1 SMP PREEMPT Thu Apr 27 12:15:09 CEST 2017 x86_64 GNU/Linux`

**Comment by olav-st** [comment]
This commit https://github.com/olav-st/screencloud/commit/70561ea1f758a918c1b87967535a18bd0e4449df adds support for Wayland when running Gnome or KWin. Other desktop environments are not supported yet since Wayland lacks official APIs for taking screenshots.

**Comment by olav-st** [comment]
Version 1.5.2 was just released with support for Wayland! https://github.com/olav-st/screencloud/releases/tag/v1.5.2

**Comment by Enovale** [comment]
Hotkeys dont actually work currently under Wayland so I added shoddy support using KDE global hotkey systems.

Even if Olav wanted to, it can't be implemented until this gets accepted: flatpak/xdg-desktop-portal#711

When that happens though, I'd love to see official support. From my look at the code, it might require a refactor though. Depends how much information XDG will need to register a hotkey.
