### ISSUE TITLE
Certain hotkey combos are not recognized.

### ISSUE THREAD

**Issue by rikai** [olav-st/screencloud#139]
Trying to change my capture keys from alt+shift+# to ctrl+shift+# and it will not let me set them.

This is on windows 7, haven't been able to test on other platforms.

**Comment by rikai** [comment]
Just a small update, realized that it works if you press the keys one at a time, which is not something i'm used to doing or i think  something that most people expect from most other programs with key combos for hotkeys. Maybe needs a usability review or some kind of note if thats how its intended to function?

**Comment by Vavooon** [comment]
It's also almost impossible to map combinations with Print Screen key like Alt+Print. Even if it was mapped it doesn't work most times when i try to make a screenshot.

**Comment by alextpedro** [comment]
I've encountered the problem with mapping Ctrl+Shift+# on Linux Mint 18.1 so it's definitely not windows specific.

**Comment by Quosimadu** [comment]
Cannot map the PrintScreen/PrtSc button Windows 10, nothing happens when pressing the button whilst in the capture fields in preferences.
