### ISSUE TITLE
Capturing All Monitors At Once

### ISSUE THREAD

**Issue by ButchDeLoria** [olav-st/screencloud#140]
Maybe I just haven't found the option for it, but I don't see a way to capture all connected displays at once with Screencloud. Capture Full Screen only captures one monitor at a time, and I'd like to be able to capture all monitors at once.

**Comment by zodman** [comment]
+1

**Comment by Deadneck** [comment]
This would be very handy, If you are running a span (eyefinity and i think nvidia surround) you can capture all monitors but while running individual screens you can only capture a single monitor at a time.

+1

Software is awesome tho, thanks :)

**Comment by starkers** [comment]
+1

Very frustrated by this :/

**Comment by zodman** [comment]
+1

**Comment by TheDoctorsLife** [comment]
+1
