### ISSUE TITLE
does not work properly capture selection on ubuntu 14.04

### ISSUE THREAD

**Issue by kvashonin** [olav-st/screencloud#141]
![2015-04-04 19 21 41](https://cloud.githubusercontent.com/assets/8190850/6993532/f0fc6122-daff-11e4-98b3-e7f59159e326.png)

**Comment by ghprod** [comment]
Just start dragging your mouse to select some area, and you will prompted with next option :)

**Comment by scythargon** [comment]
+1 here on ubuntu. I really can't select what's on the right side of the screen:(
