### ISSUE TITLE
Ubuntu Change Systray Icon

### ISSUE THREAD

**Issue by jdsampayo** [olav-st/screencloud#142]
Hello,

My status bar in Ubuntu is gray and I can barely see the icon. I see in the sourcecode that there are various systray icons but can't find in the Preferences how to select one.

How can I change it on Ubuntu, attach screen: http://screencloud.net/v/4BlL the icon is between Chrome and Skype ones.

**Comment by olav-st** [comment]
The icon should follow the theme you're using, but it would probably be a good idea to add an option for it.
