### ISSUE TITLE
Dependency broken with .deb file in Ubuntu 15.04

### ISSUE THREAD

**Issue by huyhoavnn** [olav-st/screencloud#147]
libquazip0 is replaced with libquazip1 in Ubuntu 15.04.

**Comment by MarekAG** [comment]
@huyhoavnn 
I think that I fixed it in https://github.com/olav-st/screencloud/pull/150.
I also updated the Wiki page https://github.com/olav-st/screencloud/wiki/Compiling-on-Ubuntu so now you can compile it on *buntu without problems.

As I see @olav-st stopped working on Screencloud couple months ago :disappointed:
