### ISSUE TITLE
Make pulse-audio optional?

### ISSUE THREAD

**Issue by p-boiko** [olav-st/screencloud#148]
Hi.

I had all sounds muted always, I don't need them. Recently I had to remove pulseaudio permanently and there is no way back. Now soundcloud refuses to start due to a lack of connection to pulseaudio (obviously). Is there a chance to make pulseaudio optional for those who enabled sounds only?

Thanks.

**Comment by olav-st** [comment]
ScreenCloud uses the Qt multimedia API, which probably requires pulseaudio. It might work if I change the code to avoid opening the audio device when sounds are disabled, but I'm not sure. I'll look into it when I have time.
