### ISSUE TITLE
KDE 5 Plasma issues

### ISSUE THREAD

**Issue by cmllr** [olav-st/screencloud#149]
I'm using screencloud on a clean Kubuntu installation. I'm facing following problems:

**Clipboard**

Not every link gets copied into the clipboard. I cannot reproduce this. It's only a few times per day.

**Upload**

I don't know if this is screenclouds fault, but the download is relatively slow. This problme is almost at every upload.

System:

Kubuntu 15.04, 64 bits
Screencloud 1.2.0

**Comment by olav-st** [comment]
> I can reproduce this at every screenshot. It looks like that the "screenshotting mode" is to fast and the context menu has not enough time to hide.

This can be fixed by adjusting the delay in the preferences

**Comment by squarerootfury** [comment]
Oh, well I must have overseen that option. I updated the issue text.

**Comment by llybin** [comment]
I confirm the problem.

**Comment by pfoo** [comment]
Regarding Clipboard, I noticed kde/plasma5 have many issues with clipboard no being updated as It should (at least under kubuntu 15.10). This might not be screencloud related.

Regarding "slow upload", it is not really a slow upload thing (I'm using sftp plugin, and /tmp/screencloud-sftp.log confirm that the file is uploaded very quickly). It's more like if screencloud has issue displaying the link (or realizing that the upload is finished)
