### ISSUE TITLE
Feature request: add link to clipboard when screenshot uploaded by ftp

### ISSUE THREAD

**Issue by thenamelessthing** [olav-st/screencloud#151]
Same as for uploading screenshot to screencloud. It is possible to add the same possibility to automaticly copy the link in the clipboard when we choosing to upload by ftp?

Thank you for you nice program!

**Comment by olav-st** [comment]
It should do this already if both these fields are filled out correctly.

![FTP settings screenshot](http://i.imgur.com/87l1Zsq.png)
