### ISSUE TITLE
System tray icon is always black in Mac OS X

### ISSUE THREAD

**Issue by brandongregoryscott** [olav-st/screencloud#152]
![image](https://cloud.githubusercontent.com/assets/11774799/8619705/1bcb67c6-26e7-11e5-92d8-d3b83a75522c.png)
![image](https://cloud.githubusercontent.com/assets/11774799/8619743/5bfd4eea-26e7-11e5-889e-7c7fd34ce7dc.png)
![image](https://cloud.githubusercontent.com/assets/11774799/8619782/be4b6d3e-26e7-11e5-9a56-c1df56f5fd2d.png)

The system tray icon IS still there, to the left of Caffeine, but it's not visible when setting the Mac OS X menu bar & dock to the dark mode until it is clicked. It would be nice if it inverted itself to be white or gray under dark mode.

**Comment by tusharvikky** [comment]
+1

**Comment by Shellder** [comment]
+1

**Comment by xPLd** [comment]
+1

**Comment by tobiasreinhard** [comment]
Please fix this annoying bug.

+1

**Comment by Exivus** [comment]
+1

**Comment by Xenchrarr** [comment]
+1

**Comment by olav-st** [comment]
https://github.com/olav-st/screencloud/commit/6f4cd80edbf6c99cadab9c1bb47f8b772567a892 fixes this issue.
