### ISSUE TITLE
Suggestion: Random Name

### ISSUE THREAD

**Issue by Zelakto** [olav-st/screencloud#153]
I have a suggestion, how about a feature for random name for the image to be saved as, and you can change how many characters the random code is. For example:
 
ZjTp9Wbdp9EFN4n64XAFAURxaqft56vpUCKzq7Qfa9.png
X4ShYB3uSkiUUMdLCirM9yrM.png
GBK3n5XNrTo5uxn6csbRWnNFTXrbsXKW6AUocF.png

etc etc

**Comment by ghprod** [comment]
whats purpose for having random name?

**Comment by jflory7** [comment]
@ghprod: For random screenshots that don't have a recognizable pattern. A good example of this behavior is how Gyazo names screenshots.

**Comment by Zelakto** [comment]
Exactly. :)

**Comment by boredness** [comment]
this would be really usefull

**Comment by SkyzohKey** [comment]
:+1:

**Comment by Zelakto** [comment]
I'm not sure if you guys have done this yet, but a found a solution to a random name for a screenshot. Set the "Name" of the upload to "{rnd_h}". It generates a random hash before uploading it to the server.

**Comment by ghprod** [comment]
@Zelakto Thanks for hint :+1:

**Comment by SkyzohKey** [comment]
Note that `{rnd}` will provide you a number randomized :)

**Comment by olav-st** [comment]
Closing this as a duplcate of https://github.com/olav-st/screencloud/issues/10.
