### ISSUE TITLE
Errors with Imgur plugin

### ISSUE THREAD

**Issue by Tailszefox** [olav-st/screencloud#154]
Hello. Currently running Debian Jessie, I'm trying to use the Imgur plugin with the latest version of Screencloud installed from the repository. However, I'm getting the following errors each time I start Screencloud:

```
Error in file: /home/tails/.local/share/data/screencloud/ScreenCloud/plugins/imgur/main.py
Traceback (most recent call last):
  File "<string>", line 5, in <module>
  File "/home/tails/.local/share/data/screencloud/ScreenCloud/plugins/imgur/modules/pyimgur/__init__.py", line 39, in <module>
    import requests
  File "/home/tails/.local/share/data/screencloud/ScreenCloud/plugins/imgur/modules/requests/__init__.py", line 53, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/home/tails/.local/share/data/screencloud/ScreenCloud/plugins/imgur/modules/requests/packages/urllib3/contrib/pyopenssl.py", line 69, in <module>
    ssl.PROTOCOL_SSLv3: OpenSSL.SSL.SSLv3_METHOD,
AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'
```

followed by
```
Failed to call ImgurUploader.isConfigured()
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name ImgurUploader
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'ImgurUploader' is not defined
```

And when trying to configure the plugin:
```
Failed to call ImgurUploader.showSettingsUI()
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'imgur_u' is not defined
```

The Imgur plugin is thus unusable. Any idea what could be the cause?

**Comment by Tailszefox** [comment]
Okay, I managed to make the plugin work again, though it's not very convenient. Basically, the Imgur plugin is using outdated versions of pyimgur and requests, so I had to grab the latest versions. If someone ends up with the same issue, here's how I solved it:

1. Disable the Imgur plugin if it's enabled and close ScreenCloud
2. Clone the plugin repository with `git clone git@github.com:olav-st/screencloud-plugins.git`
3. `cd screencloud-plugins`
4. `git submodule init`
5. `git submodule update`
6. `cd imgur/deps/pyimgur`
7. `git checkout master`
8. Repeat 7. in the `imgur/deps/requests` folder
9. `cd ../../..` to go back to the `screencloud-plugins` directory 
10. Copy the `imgur` directory into your Screencloud plugin directory, which should be at `~/.local/share/data/screencloud/ScreenCloud/plugins`
11. Restart ScreenCloud, the Imgur plugin should be enabled and ready to be configured

As I said, that's a lot of steps to get it working, so I hope it'll be fixed at some point so it's not necessary to do that anymore.

**Comment by Tailszefox** [comment]
Moving this issue to the plugins repository.

**Comment by Pharmasolin** [comment]
In 2. step you this command if you have error in guide upper.
git clone https://github.com/olav-st/screencloud-plugins.git

For me this guide helped when i upgrade my Ubuntu from 15.04 to 15.10

http://i.imgur.com/RL28aEq.png
