### ISSUE TITLE
Get rid of .png extension in URL that gets copied.

### ISSUE THREAD

**Issue by ghost** [olav-st/screencloud#155]
Can we please get an option to get rid of the .png extension that it puts in the URL?

Example: <mydomain>.com/image_name.png
What I want: <mydomain>.com/image_name

Can we please get this feature? Or if it is already possible, how can I do it?

Thanks so much!

**Comment by williamgp11** [comment]
Has anyone seen this?

**Comment by BoomLiam** [comment]
This is something you have to do with a .htaccess file instead. It's pretty simple, just create a re-write rule which removes the .png extension like so:

RewriteEngine On

RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^([^./]+\.png)$ /i/$1 [L,NC]

For more information, google htaccess file
