### ISSUE TITLE
On Linux, screenshotting a window is always off-center

### ISSUE THREAD

**Issue by jwflory** [olav-st/screencloud#156]
I am running Fedora 22 4.1.3-200.fc22.x86_64. Whenever I take a screenshot of a window using Shift+Control+3, my screenshots are always off center for whatever window I am trying to screenshot.

_Example_:
![Example](http://i.j-f.co/u/69ca452f823238b2a2074140b5ed59e1.png)

You can see in this image that the upper-left corners are captured by the edges, and a significant amount of extra screen space is present on the lower-right corners.

**Comment by olav-st** [comment]
I haven't seen this on Linux before, which desktop environment are you using?

**Comment by jflory7** [comment]
I'm using GNOME 3.18, Fedora 23. However, I've noticed this as far back 
as Fedora 21, which I think was GNOME 3.15 or 3.16.

--
Cheers,
Justin W. Flory
jflory7@gmail.com

**Comment by jflory7** [comment]
@olav-st Also worth noting is that it doesn't seem to happen for windows that are full screen, only windows that take up partial space on the screen.

For example, this screenshot of my Firefox window appears to be fine.
![Fullscreen Firefox](https://i.j-f.co/u/6156853ddc6a87fe9e6e520ebc396b35.png)
