### ISSUE TITLE
Feature request: Upload automatically

### ISSUE THREAD

**Issue by sandipkc7** [olav-st/screencloud#161]
I want to request feature for automatically uploading upon selection on screen. Currently I have to press enter key after selecting area at screen.

**Comment by nxxv0** [comment]
Yeah, would be cool :c Want this feature too.

**Comment by TheDoctorsLife** [comment]
The issue with this is what if I were to make the wrong selection? Now I have a screenshot that doesn't have what I wanted uploaded to where ever.

**Comment by RandyVG** [comment]
All of the above - I first felt that ENTER was an extra step. Then I said to myself, "but something has to tell it when you're done and I sure don't want it to be when I lift up on the mouse button." So if the feature were added it would have to be optional. I am comfortable with pressing enter now.

**Comment by TheDoctorsLife** [comment]
If this isn't the default behavior that should be good.
