### ISSUE TITLE
No upload sound in 1.2.0

### ISSUE THREAD

**Issue by Zeluboba** [olav-st/screencloud#164]
Hello,
after I've updated ScreenCloud to 1.2.0 from 1.0.6(probably) I don't get the sound when the screenshot is uploaded.

I'm on Windows. Didn't test with my Linux version.

**Comment by SerDIDG** [comment]
Some for me on OSX 10.11

**Comment by olav-st** [comment]
Duplicate of https://github.com/olav-st/screencloud/issues/131.
