### ISSUE TITLE
Uploading to FTP makes plasma panel freezes for about 20 seconds

### ISSUE THREAD

**Issue by milansimek** [olav-st/screencloud#170]
I'm experiencing the following issue when using KDE5:
1. I take a screenshot and upload to FTP
2. The plasma panel becomes unresponsive for 20 seconds
3. If I paste in a window, this window also becomes unresponsive
4. 20 seconds later the link is copied to the clipboard and the panel and window respond again.
5. During the freeze the screencloud icon does show an upload arrow 

The issue is only present in KDE, not in Unity or XFCE.

Any ideas? 

Thanks!

**Comment by Gnat008** [comment]
I am also experiencing this, except I am trying to upload to Imgur. Here is some of my system info: https://imgur.com/u7jqDNd
Using ScreenCloud version 1.2.0

Hope this helps!

**Comment by Psaproxy** [comment]
My too have this problem when save image to any service, also clipboard.

screencloud 1.4.0
kde plasmashell 5.8.6
Linux psa 4.19.0-0.bpo.4-amd64 #1 SMP Debian 4.19.28-2~bpo9+1 (2019-03-27) x86_64 GNU/Linux
