### ISSUE TITLE
Huge issues on linux

### ISSUE THREAD

**Issue by Zeluboba** [olav-st/screencloud#171]
Hello, using last version from ubuntu store. (It's 1.1.0 probably)
The problems are:
* checking for update doesn't work. It's "Loading..." permanently.
* there's red 'error!' warning on account details pane, I tried logging out and I can't log in with same email and password (worked on website)
* the modules list isn't loading
* imgur module doesn't work, it says about wrong key or something, receiving new one doesn't work as well.
Also would be awesome if you'll fix https://github.com/olav-st/screencloud/issues/164

**Comment by olav-st** [comment]
Don't use the version from the Ubuntu Software Centre, it's massively out of date.

**Comment by Zeluboba** [comment]
@olav-st what's the problem updating the repo? It's easier for users to update it via 'apt-get update' than downloading package, compiling and installing it every time.
Anyway, #164 is windows bug and it's very annoying, I need to check if sshot is really uploaded each time.

**Comment by olav-st** [comment]
I've stopped using the ubuntu store, if you add the repo on OBS you can still update with `apt-get update`
