### ISSUE TITLE
[qt5-port] Some issues

### ISSUE THREAD

**Issue by AlfredoRamos** [olav-st/screencloud#174]
Hi there.

I'm glad you're still working on the Qt5 port, I hope I can help somehow.

Today I finally could compile the Qt5 version but there's some issues that maybe you're already aware.

- This might be an Arch specific issue but QuaZip (Qt5) is located in `quazip5`, I made a [patch](https://aur.archlinux.org/cgit/aur.git/plain/quazip_qt5_fix.patch?h=screencloud-git) for the AUR package.

- `FindPythonQt_QtAll.cmake` always fails to find `PYTHONQT_QTALL_INCLUDE_DIR`, I have to set the path with cmake ([PKGBUILD](https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=screencloud-git)).

    I'm not really sure about this one since I had to compile the PythonQt lib "by hand" to get it work with Qt5. I made an AUR package ([pythonqt-qt5](https://aur.archlinux.org/packages/pythonqt-qt5/)). 

    I installed the header in `/usr/include/PythonQt/extensions/PythonQt_QtAll/PythonQt_QtAll.h`, this might be the problem but I don't know where it has to be placed.

- ~~There's no system tray icon under LXQt, I don't know why but `QSystemTrayIcon::isSystemTrayAvailable` always returns `false`. I'm currently in Cinnamon and it works just fine.~~ It seems to be something wrong with the LXQt version I have installed, since I have the same issue with other apps.

- It fails to get account data, it gives ["Failed to parse response from server"](https://i.imgur.com/aJa0LVT.png), the same when [uploading to screencloud.net](https://i.imgur.com/aBSVMfl.png).

- Imgur upload plugin is broken, it throws some errors:

```
Error in file: /home/abaddon/.local/share/screencloud/ScreenCloud/plugins/imgur/main.py
Traceback (most recent call last):
  File "<string>", line 5, in <module>
  File "/home/abaddon/.local/share/screencloud/ScreenCloud/plugins/imgur/modules/pyimgur/__init__.py", line 34, in <module>
    from urlparse import urlparse
ImportError: No module named 'urlparse'

---------------

Failed to call ImgurUploader.isConfigured()
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name 'ImgurUploader'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'ImgurUploader' is not defined

---------------

Failed to call ImgurUploader.showSettingsUI()
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'imgur_u' is not defined
```

I managed to fix the first one with:

```
try:
    from urlparse import urlparse
except ImportError:
    from urllib.parse import urlparse
```

But I can't fix the others, I don't even know Python :/

My system
```
OS:        Arch Linux x64
GCC:       5.3.0
Qt5:       5.5.1
PythonQt:  3.0 (Qt5 build)
```

PS: Qt Mobility is still needed in Qt5? [info](https://forum.qt.io/topic/24884/qt-mobility-api-in-qt-5)

**Comment by olav-st** [comment]
> FindPythonQt_QtAll.cmake always fails to find PYTHONQT_QTALL_INCLUDE_DIR, I have to set the path with cmake (PKGBUILD).

This cmake module was just a hack I did to make it compile with the new PythonQt version. I'm not sure how to do it "properly", as I haven't seen any other open source projects using both Qt5 and PythonQt.

> There's no system tray icon under LXQt, I don't know why but QSystemTrayIcon::isSystemTrayAvailable always returns false. I'm currently in Cinnamon and it works just fine.

Could be a Qt bug?

> It fails to get account data, it gives "Failed to parse response from server", the same when uploading to screencloud.net.

I just pushed https://github.com/olav-st/screencloud/commit/18b279533ff9195ed2e875735cd6440d5bd7a326 that fixes this. You'll have to log out and in again because the tokens were not saved properly before.

**Comment by olav-st** [comment]
> Imgur upload plugin is broken, it throws some errors:

I updated to the latest pyimgur which should help, see https://github.com/olav-st/screencloud-plugins/commit/04f561680ffce3d96e8149a0b7bcf93eb309034a.

**Comment by olav-st** [comment]
> FindPythonQt_QtAll.cmake always fails to find PYTHONQT_QTALL_INCLUDE_DIR, I have to set the path with cmake (PKGBUILD).

I've update the cmake files and it should find it now. It does on Ubuntu, but I'm using a fork of PythonQt, see https://github.com/olav-st/screencloud/blob/qt5-port/.travis.yml.

**Comment by AlfredoRamos** [comment]
I'll test it now :+1:

PS: Should I start using the master branch? I can see a fix for QuaZip 5 (5a493dd), but it is only in the master branch.

**Comment by olav-st** [comment]
I've merged the qt5 port into master and will continue to work on it there :)

**Comment by AlfredoRamos** [comment]
Everything works fine so far.

However there are still some problems with the imgur plugin, I'm opening a new issue in the correct repository.

**Comment by olav-st** [comment]
:+1:
Also, heads up, I've been trying to make the CMake install use standard dirs, this might break some things.

**Comment by AlfredoRamos** [comment]
`xdg-utils` (`xdg-icon-resource` and `xdg-desktop-menu`) can't install the resources, so it ends up installing the app without icons and `*.desktop` entry.

```
-- Install configuration: ""
xdg-icon-resource: No writable system icon directory found.
xdg-icon-resource: No writable system icon directory found.
xdg-icon-resource: No writable system icon directory found.
xdg-icon-resource: No writable system icon directory found.
xdg-icon-resource: No writable system icon directory found.
xdg-desktop-menu: No writable system menu directory found.
```

Also, I hadn't noticed that, if I have Qt4 installed even if I set the flags to compile with Qt5 (`-DQT_USE_QT5=ON` and `-DQT_QMAKE_EXECUTABLE=/usr/bin/qmake-qt5` flags) it compiles with Qt4.

If I only have Qt5:

```
Found unsuitable Qt version "5.5.1" from /usr/bin/qmake-qt5
-- Couldn't find any version of QtMobility.
```

QtMobility no longer exists in Qt5, It has been splitted into other modules.

**Comment by AlfredoRamos** [comment]
I'm closing this since 4 of the 5 issues in the first post have been fixed and 1 is invalid.
