### ISSUE TITLE
SSL conection error

### ISSUE THREAD

**Issue by Nullfati** [olav-st/screencloud#175]
I have this error:
![default](https://cloud.githubusercontent.com/assets/9294709/11794739/86e0fb84-a2bb-11e5-93de-c272fb738989.png)

**Comment by TearsOfSky** [comment]
Same error on Linux Mint.

**Comment by Nothing4You** [comment]
Reported this as olav-st/screencloud-plugins#20 aswell (windows user here).

The bundled python libraries need to get updated

**Comment by Zeluboba** [comment]
@olav-st upvote, updated the imgur module and it stopped working. 1.2.0 on windows

**Comment by Firewall** [comment]
Same here, v1.2.0 on Elementary OS Freya

**Comment by debug-hf** [comment]
Same here, windows 7

**Comment by Spokuha** [comment]
same problem here, any fix?

**Comment by olav-st** [comment]
I'll probably have to update the version of Python shipped with the app. I've been working on a Python 3 version for a while anyway so I'll try to get it ready quickly :)

**Comment by olav-st** [comment]
This https://github.com/olav-st/screencloud-plugins/commit/217420a3b90ee65ef6ba04343c75456187a816ab should work as a temporary fix. It's not great since SSL verification wont work properly, but its better than nothing. I'll remove it once a newer python version is used.

**Comment by Firewall** [comment]
Yup fix worked. Thanks!

**Comment by Nullfati** [comment]
How fix:
Install Python 3.5.1 and update ScreenCloud with plugins.
