### ISSUE TITLE
Python module

### ISSUE THREAD

**Issue by AlfredoRamos** [olav-st/screencloud#182]
Currently the `ScreenCloud.py` module is installed in `/usr/share/screencloud/modules`, so plugins like Imgur fails to import it.

I've read that they must be installed in `/usr/lib/python{PYTHON_VERSION}/site-packages`, but I don't know how CMake can handle that. I've made a symlink to `/usr/lib/python3.5/site-packages` so the imgur plugin can work properly.

Some LibreOffice modules append the non-standar path (`sys.path.append('/path/')`), so when importing Python doesn't throw an error.

**Comment by olav-st** [comment]
https://github.com/olav-st/screencloud/commit/e6ee93058c68f8c2301c7eb6f3cd19a158aac54d should fix this. I opted to add a non-standard path since it dosen't make sense to import the ScreenCloud module from regular python.
