### ISSUE TITLE
SC can only do a screenshot on the primary screen on MATE when using dual screen

### ISSUE THREAD

**Issue by cmllr** [olav-st/screencloud#185]
Using the MATE Desktop, Screencloud can only access the primary screen on a dual screen setup.

Also, both screens will show the same image while cutting out a selection on the screen.

A screenshot of the secondary screen is (with the selection tool) not possible.

**Comment by mmuruev** [comment]
Almost the same problem but on Mac OS X.. possible make pictures only from primary screen.. second screen just went corrupted then screen 'selection' activated

**Comment by squarerootfury** [comment]
Additional information: It seems that this issue affects a set of desktops and systems. Screencloud on Cinnamon has the same issue.

**Comment by VojtecHouzvicka** [comment]
Having the exact same issue on Mac OS X

**Comment by Pablohn26** [comment]
Same issue here. 
Fedora and MATE Desktop.
