### ISSUE TITLE
E-mail doesn't work

### ISSUE THREAD

**Issue by forteller** [olav-st/screencloud#186]
Hi, Olav. I tried sending you an e-mail a week ago, but it didn't reach you:

Delivery to the following recipient has been delayed:

```
 contact@screencloud.net
```

Message will be retried for 2 more day(s)

Technical details of temporary failure:
The recipient server did not accept our requests to connect. Learn more at https://support.google.com/mail/answer/7720
[(0) screencloud.net. [128.199.45.43]:25: socket error]

**Comment by omnibs** [comment]
Dropping in on the issue, I'm trying to contact Olav about billing problems on the premium, no answer yet.

**Comment by olav-st** [comment]
Thanks for letting me know, I'd forgotten to change the DNS-records to the appropriate mailserver. I've done so now, but it might take a while to propagate.
