### ISSUE TITLE
Minute variable is always set to 01

### ISSUE THREAD

**Issue by angristan** [olav-st/screencloud#187]
If I want my screenshot name like this : `screenshot_%d-%m-20%y_%H-%m`, I should have for exemple this : `screenshot_09-01-2016_19-43.png`. But I always get the last one like this : `screenshot_09-01-2016_19-01.png`. Alway 19:01, 20:01; etc

**Comment by DerSmythe** [comment]
I suspect by making your last %m a capital %M it will resolve your problem as 'm 'is for month, 'M' is for minute. Try screenshot_%d-%m-20%y_%H-%M

**Comment by Angristan** [comment]
Okay, I'm dumb :D 
Do you know if I can put some random var in the name ?

**Comment by DerSmythe** [comment]
Try something like "%y%m%d_%H%M%S_{rnd_s}". It allows sorting by datetime while making it random

**Comment by Angristan** [comment]
Awesome, thank you :)

**Comment by Angristan** [comment]
Since the last update, all my files are named like this : `screenshot_22-08-2016_b'oMpFhZQR'` instead of `screenshot_22-08-2016_oMpFhZQR` for instance. Why is there `b'....'` now ?

**Comment by Angristan** [comment]
Any idea ?

**Comment by Angristan** [comment]
The problem seems to come from here https://github.com/olav-st/screencloud/blob/54cd0c34330e27a5702f1f47e0a7e9f31b9b17dd/res/modules/ScreenCloud.py#L29

**Comment by Angristan** [comment]
This commit is the source of the problem https://github.com/olav-st/screencloud/commit/e8eb4a055e38643aeacb3806d3626b4c3f897e7f

**Comment by olav-st** [comment]
This is because of differences between Python 2 and Python 3.

**Comment by Angristan** [comment]
I see it has been fixed here https://github.com/olav-st/screencloud/issues/219, but there is no version 1.3.1 for Windows on the website ^^
