### ISSUE TITLE
can't use (select) FTP upload anymore (settings are setup correctly, python problem I guess)

### ISSUE THREAD

**Issue by unknownp** [olav-st/screencloud#189]
Hello,

I've always been using ScreenCloud to upload directly to my ftp and then have the link on the clipboard.
Recently I changed it shortly to "save to ScreenCloud", since then I can not select FTP again.
http://puu.sh/mpPLE/143eb087a5.png

The settings are still the same and correct, I triple checked. Reinstalled, repaired, deleted all temp files from appdata, programfiles and what not.

Of course I googled to find a solution and saw this
https://github.com/olav-st/screencloud/pull/120

I have python installed (C:\Python27), but never really used it. Was just starting to teach myself a bit when I discovered the ScreenCloud issue.

Is there anything you can do to help me out on this? I tried what's written on the github post there, but I could not really get it working.
You even commented on it with:

olav-st commented on Jan 8, 2015
but your link does not work anymore

**Comment by olav-st** [comment]
Do you get any errors from the FTP plugin? What does it say if you try to select "Ask me.." and then choose FTP from the dropdown the next time you take a screenshot?

**Comment by unknownp** [comment]
Hey
my ftp settings are set correctly, they work on filezilla and have worked before wich makes this strange ^^
error shown: http://puu.sh/msiUn/6d1bd6f240.png

with the fix he posted I get a few error popups
1.
http://puu.sh/msj55/0efd125c86.png

2.
http://puu.sh/msj8o/c57aae7070.png

3.
http://puu.sh/msj9G/14ae844d0d.png

4.
http://puu.sh/msjaF/99bf5d0edd.png

**Comment by unknownp** [comment]
do you happen to know the issue?
