### ISSUE TITLE
I can't get plugin list and plugins. 

### ISSUE THREAD

**Issue by bgencacat** [olav-st/screencloud#190]
I cant get plugin list or plugin with and without url.

http://screencloud.net/v/t4J1

I'm using Ubuntu 15.10

**Comment by olav-st** [comment]
Strange, it works for me..
Do you get any output if you run SC from the terminal?

**Comment by bgencacat** [comment]
I'm new in Ubuntu, can you tell me what should I do for give information? Which command's output?

**Comment by olav-st** [comment]
Try opening a terminal and running `screencloud` (alternatively you can run `/opt/screencloud/screencloud.sh` if the first command dosen't work)

**Comment by bgencacat** [comment]
When I'm run this command if screencloud wasn'T running its opening. else it says ScreenCloud is already running. Please close the running instance before starting a new one.

**Comment by olav-st** [comment]
Does the terminal show any messages when trying to load the plugin list?

**Comment by bgencacat** [comment]
The problem is: there isn't a problem
https://screencloud.net/v/oZ2o

**Comment by bgencacat** [comment]
I solve it using my hosting but maybe new users cant do it. I dont know maybe problem is my dns adresses.
