### ISSUE TITLE
Upload failed

### ISSUE THREAD

**Issue by ipedrazas** [olav-st/screencloud#192]
I'm getting an error:

```
Upload Failed!
Illegal parameters. name and description must be a string, file must be a jpg, png or gif
```

Login into the website doesn't work either :sob:

**Comment by studioart** [comment]
Yes, I can confirm that!
Since today, I have exactly the same error message.

@ipedrazas have you gone to the online site https://screencloud.net/?

When going to the site https://screencloud.net/, then - with this error above in mind - I am NOT LOGGED IN.
And when I try to login, then the login failed without any notice (password and email is right).
I tried to recover the password, a confirmation mail arrives me, I clicked the confirmation link, but I still cannot log me in. 

Maybe  the error mentioned above is the reason of that fact.

**Comment by olav-st** [comment]
I've tried clearing the cache on the server. Do you still get the error?

**Comment by studioart** [comment]
Great, works fine now! Thanks a lot!!

**Comment by ipedrazas** [comment]
Error is gone, so, it was a problem with the cache of the server, then?

**Comment by studioart** [comment]
This error is currently again there!

**Comment by ipedrazas** [comment]
yep, it's happening again :sob:

**Comment by devmoonshine** [comment]
Yeah, exact same error to me, too.
But today, at this moment, - this is the first appearance of this bug for me.
Cache cleaning didn't help..

**Comment by studioart** [comment]
Yes, happening again:
I can't login at screencloud's website.
And when I try to upload at Windows 7 then I get an error:
"Upload failed! Illegal parameters, name and description must be a string, file must be a jpg, png or gif".

**Comment by Abyss281290** [comment]
I have the same issue right now at ubuntu 14

**Comment by olav-st** [comment]
Should be up and running again now.

**Comment by studioart** [comment]
works again perfectly, thanks a lot!

**Comment by 4026** [comment]
Hi there. I'm observing these exact same symptoms again at the moment. Is there a server-side switch that needs to be flipped to fix this?

**Comment by olav-st** [comment]
There were some space issue on the server. It should be up and running again now.

**Comment by 4026** [comment]
Yep, that's fixed it. Thanks!

**Comment by bohdamyrs-egnaroinc** [comment]
Hi guys.  Again the same bug :(  Yesterday evening it worked. (11 hours ago)

**Comment by bohdamyrs-egnaroinc** [comment]
Hm. Now works. Thx!

**Comment by tagrudev** [comment]
@olav-st I am having this error again, I am using the Latest Version: `1.3.0` is it possible to be a server fault again ?

**Comment by nortmas** [comment]
Same for me now :( and from time to time....

**Comment by AlexMakarenko** [comment]
The same error, can't login, can't upload screenshot. Could you fix it asap?

**Comment by DenisBabarykin** [comment]
Same error
