### ISSUE TITLE
Dropbox plugin python error upload failed to call dropbox uploader.upload()

### ISSUE THREAD

**Issue by mescalito** [olav-st/screencloud#193]
Hi there!
I'm using windows7. This is the error when using Dropbox plugin:

![1](https://cloud.githubusercontent.com/assets/687283/12850250/d05a0efe-cbf1-11e5-91c3-a863def3559f.png)

```
py> 
C:\Users\Antares\AppData\Local\screencloud\ScreenCloud/plugins/dropbox\modules\urllib3\util\ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
C:\Users\Antares\AppData\Local\screencloud\ScreenCloud/plugins/dropbox\modules\urllib3\util\ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
C:\Users\Antares\AppData\Local\screencloud\ScreenCloud/plugins/dropbox\modules\urllib3\util\ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InasdsecurePlatformWarning
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'asdsecurePlatformWarning' is not defined
```

Any idea what is going on?

**Comment by wertlex** [comment]
+1. Same issue on Ubuntu 14.04

**Comment by wertlex** [comment]
@mescalito btw, this is why this happens: https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning

If you can update to Python 2.7.9 + - do that. 

But guys, what should I do on Ubuntu 14.04 where 2.7.6 is default? 

Upgrade seems to be not good idea. And other two ways described are not user-friendly.
Any ideas?
Maybe just that will help: https://urllib3.readthedocs.org/en/latest/security.html#disabling-warnings ?

**Comment by jeserkin** [comment]
+1

One time appears, one time uploads, etc.

**Comment by mescalito** [comment]
@wertlex , I did install python 2.7.11, after that I located the urllib3 folder in C:\Program Files (x86)\Python27\Lib\site-packages\pip\_vendor\requests\packages\urllib3, then copy all the content into the dropbox folder: C:\Users\Antares\AppData\Local\screencloud\ScreenCloud\plugins\dropbox\modules\urllib3\... and it didn't work.

Do you have any other idea or maybe I did something wrong you can point me out
Thanks!

**Comment by voult2** [comment]
+1 

Waiting for a new update from ScreenCloud to solve this..

**Comment by djzurawski** [comment]
+1
Still same problem after upgrading to python 2.7.11 on Linux Mint

![screenshot at 22-14-55](https://cloud.githubusercontent.com/assets/7685869/13864921/4ebb9cd8-ec6b-11e5-84a1-8bf4f006bd99.png)

**Comment by olav-st** [comment]
Probably related to https://github.com/olav-st/screencloud-plugins/issues/20.
I'll try to do the same temporary fix.

**Comment by olav-st** [comment]
I just pushed https://github.com/olav-st/screencloud-plugins/commit/467f90f44c3e2a33205c7c4d56bc31a200584c7f
Try restarting ScreenCloud and updating.

**Comment by mescalito** [comment]
Holly shit! it is working again! good job @olav-st . By the way I just upgrade my account to premium to show my support, if you keep fixing bugs I'll be glad to keep sponsoring ;) thanks!
