### ISSUE TITLE
Error after running the Screencloud on the xubuntu 15.10

### ISSUE THREAD

**Issue by ant-** [olav-st/screencloud#195]
There is a known issue after installing Screencloud on xubuntu. But the workaround doesn't work for me.
`/opt/screencloud/screencloud: error while loading shared libraries: libquazip.so.1: cannot open shared object file: No such file or directory
`

**Comment by dafanasiev** [comment]
workaround not work?
`
sudo ln -s /usr/lib/x86_64-linux-gnu/libquazip.so.1.0.0 /usr/lib/x86_64-linux-gnu/libquazip.so.1 
`
