### ISSUE TITLE
Autodelete

### ISSUE THREAD

**Issue by columb** [olav-st/screencloud#2]
A timer to delete images. Would be nice to keep my dropbox/imgur accounts clean.

**Comment by boselfje** [comment]
As I can see, Screencloud now had a timer for autodelete, 'cause it's asking me to change to premium, else some of my screenshots will be lost, but it is warning be for screenshots taking 3 months ago, asweel as for shots taking only 2 months ago. So I was wondering what is the actual time to keep my screenshots on the screencloud server?

**Comment by olav-st** [comment]
Currently screenshots are kept for 2 months after they last were viewed. This applies only to free accounts of course.
