### ISSUE TITLE
Problem with Login on Windows 10

### ISSUE THREAD

**Issue by GatoPresto** [olav-st/screencloud#200]
I have problem on windows 10 when I choose "I already have a ScreenCloud account" and try to login, I get the message: "Login failed. Please check your email, password and internet connection".

I haven't any problem on ubuntu 15.10 or website.

I can't find log file for attach it. If program has log file, tell me that I can find it.

**Comment by olav-st** [comment]
ScreenCloud only logs to stdout/stderr, but you can generate a logfile by running it like this from a command line window:
`ScreenCloud.exe 1> output.txt 2>&1`

**Comment by CharlotteDunois** [comment]
I got the same issue on Windows 7. The logfile contains the following

```
[INFO] "Loaded 0 plugin(s)" 
[INFO] "Using bundled icon: :/systray/trayicon-blue.svg" 
[INFO] "" 
[1;33m[WARN][0m "https://api.screencloud.net/1.0/oauth/access_token_xauth returned: " 
[1;33m[WARN][0m "https://api.screencloud.net/1.0/oauth/access_token_xauth returned error" 
```

**Comment by GatoPresto** [comment]
Yes, I have the same log file
```
[INFO] "Checking https://raw.githubusercontent.com/olav-st/screencloud-plugins/master/plugin-list.xml for redirect" 
[1;33m[WARN][0m "https://api.screencloud.net/1.0/oauth/access_token_xauth returned: " 
```

**Comment by phil2key** [comment]
I have the same error message when I try it from Windows 10.

**Comment by charkyem** [comment]
I'm getting this same error on 8.1 pro, and have been for some weeks now, Tried sending an email to no avail. I can log into the website just fine, and my PC (running Mint) is still taking screenshots to the account fine.

**Comment by CharlotteDunois** [comment]
@olav-st Has there been any progress on a fix and/or workaround?

**Comment by mhawk0** [comment]
I have the same issue, can't log in to my account in the app, win 10.

**Comment by kalexi** [comment]
having the same issue. any help?

**Comment by Kris-Simpson** [comment]
I have the same issue on Windows 10 build 10586.494. All works fine on Ubuntu 14.04/website.

**Comment by phil2key** [comment]
Any new updates?
