### ISSUE TITLE
Missing system tray icon in the mate desktop environment

### ISSUE THREAD

**Issue by hunterforcode** [olav-st/screencloud#201]
screenshot https://imgur.com/H2p5XEj

It's an excellent tool for me but minor problem appears in the mate desktop as the screenshot shows.
I have libqt4-svg package installed in Linux Mint 17.2. 
Besides, I run screencloud from terminal and log output is pasted here. 

$ screencloud 
"sni-qt/6522" WARN  18:06:39.751 void StatusNotifierItemFactory::connectToSnw() Invalid interface to SNW_SERVICE 
[INFO] "Loaded 2 plugin(s)" 
[INFO] "Using bundled icon: :/systray/trayicon-gray.svg" 

I don't know how to solve the problem, perhaps it's related to the mate theme?

**Comment by abonec** [comment]
After update to 1.3.0 icon is missing in system tray. Icon showed correct in previous version.

I did not noticed which version being used before but it was installed about 3-4 month ago from now.

System - Ubuntu 16.04, i3wm - 4.12

**Comment by modder2** [comment]
There are no updates on this issue?
