### ISSUE TITLE
Ubuntu 15.10 version will not install in 16.04.

### ISSUE THREAD

**Issue by paulpoco** [olav-st/screencloud#204]
No version for Ubuntu 16.04.

Sometimes you can install a version for a previous release but not in this case.

> sudo apt-get install screencloud
> Reading package lists... Done
> Building dependency tree  
> Reading state information... Done
> Some packages could not be installed. This may mean that you have
> requested an impossible situation or if you are using the unstable
> distribution that some required packages have not yet been created
> or been moved out of Incoming.
> The following information may help resolve the situation:
> 
> The following packages have unmet dependencies:
>  screencloud : **Depends: libqtmultimediakit1** but it is not installable
> E: Unable to correct problems, you have held broken packages.

**Comment by God3us** [comment]
same problem ... i dont have any solution for moment but maybe we can try to use snap to solve this problem?

**Comment by zerocool42** [comment]
Same problem here, would be nice to see a 16.04 version soon.

**Comment by JarrenceMelie** [comment]
Hi, guys,
temporary fix for the issue:
1 Add to your _/etc/apt/sources.list_ 
_deb http://cz.archive.ubuntu.com/ubuntu wily main universe_
(change cz.archive.ubuntu.com/ubuntu to a necessary server).
2 Do apt-get install _libqtmultimediakit1_.
3 Install (or reinstall) Screencloud.

**Comment by cfebs** [comment]
Thank you @JarrenceMelie that procedure worked!

For those trying you can use any archive local url (ex. `deb http://us.archive.ubuntu.com/ubuntu wily main universe`)

**Comment by zerocool42** [comment]
Still not working for me, needs a lot of dependencies:

` screencloud : Depends: libqt4-designer (>= 4:4.5.3) but it is not going to be installed
               Depends: libqt4-svg (>= 4:4.5.3) but it is not going to be installed
               Depends: libqxt-core0 but it is not going to be installed
               Depends: libqxt-gui0 but it is not going to be installed
               Depends: libquazip0 but it is not installable or
                        libquazip1 but it is not going to be installed
`

**Comment by Epizefiri** [comment]
@zerocool42 same error here, that procedure worked:

>   sudo sh -c "echo 'deb http://download.opensuse.org/repositories/home:/olav-st/xUbuntu_15.10/ /' >> /etc/apt/sources.list.d/screencloud.list"
> sudo apt-get update
> sudo apt-get install screencloud

**Comment by forteller** [comment]
That didn't work for me:

'''
W: GPG error: http://download.opensuse.org/repositories/home:/olav-st/xUbuntu_15.10  Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 1BE1E8D7A2B5E9D5
W: The repository 'http://download.opensuse.org/repositories/home:/olav-st/xUbuntu_15.10  Release' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
'''

I really hope @olav-st will be able to update this soon. It's really a must have for me at this point. :)

**Comment by likeon** [comment]
You can download the package [here](http://packages.ubuntu.com/precise/libs/libqtmultimediakit1) (links at the bottom of the page).

1. wget http://de.archive.ubuntu.com/ubuntu/pool/universe/q/qtmobility/libqtmultimediakit1_1.2.0-1ubuntu2_amd64.deb
2. sudo dpkg -i libqtmultimediakit1_1.2.0-1ubuntu2_amd64.deb
3. sudo apt-get install -f

**Comment by forteller** [comment]
I'm very happy OMG Ubuntu wrote about how to install Screencloud: http://www.omgubuntu.co.uk/2016/06/force-install-screencloud-ubuntu-16-04

Hopefully such great publicity will be a boost to @olav-st :)

**Comment by RomanSteinberg** [comment]
I have ubuntu 16.04. These instructions didn't help to install screencloud app.
