### ISSUE TITLE
Save to multiple locations

### ISSUE THREAD

**Issue by etherz10** [olav-st/screencloud#207]
I used to use TinyGrab which allowed me to save to a local directory as well as upload the screenshot to a directory on my SFTP server.

It seems Screencloud only allows one or the other.

**Comment by etherz10** [comment]
@olav-st Is Screencloud still under development?

**Comment by olav-st** [comment]
@etherz10 I work on it when I have time. Right now I have a few exams coming up so I won't be able to work on it in the next few weeks.

**Comment by kolorafa** [comment]
Upvote - as for me it's the one key feature that is missing after moving from HotShots.

Without it I rather use local file and dropbox sharing rather than use only online storage, i got burned to many times by random online services.

Also +1 to Custom domainshost on ScreenCloud hosting
