### ISSUE TITLE
Date in file name

### ISSUE THREAD

**Issue by etherz10** [olav-st/screencloud#208]
Currently when saving locally Screencloud seems to only allow you to define the time when the screenshot was taken.

It would be nice if you could name files date then time.

**Comment by Thor77** [comment]
`ScreenCloud.formatFilename` (the function, the localfile-plugin is using to generate the filename from your input) is just using [`time.strftime`](https://docs.python.org/3/library/time.html#time.strftime).
For example `%Y-%m-%d_%H-%M-%S` would result in `year-month-day_hour-minute-second`

**Comment by LeBaux** [comment]
There are still 2 minor yet annoying (poor UX) problems with setting the filename format.

1. The preview of the file name format is not working properly:
![Peek 2020-07-27 19-59-screencloud-file-names](https://user-images.githubusercontent.com/5657511/88575189-c1247680-d043-11ea-8012-e94d7e12f7f9.gif)


2. The filename format could do with a picker, similar to FlameShot:
![image](https://user-images.githubusercontent.com/5657511/88574528-c208d880-d042-11ea-9fcf-3ff7c52824fa.png)
