### ISSUE TITLE
Difficulty grabbing screen on a 27" thunderbolt with OS X El Capitan (10.11.5)

### ISSUE THREAD

**Issue by changeableface** [olav-st/screencloud#209]
Setup: MacBook Pro 13-Inch running OS X El Capitan (10.11.5) with the screen res set to "more space" (yeah, _really_ helpful descriptions Apple!) and one 27" Thunderbolt.

I normally keep the lid open on my MacBook and use both screen, when doing so if I grab the MacBook screen it works as expected. If I try this on the thunderbolt screen it seems to shift to the left and get context off another desktop space. 

If I close the lid and use just the Thunderbolt screen it works as expected. 

I've attached shot of the desktops I'm trying to capture, and then what happens when I initiate a capture on the thunderbolt. 

Screen I want to capture, it's just the desktop as a demo:
![imag0194](https://cloud.githubusercontent.com/assets/840144/15475658/107fcbde-2103-11e6-9847-b7fee51babf4.jpg)

What it then captures:
![imag0195](https://cloud.githubusercontent.com/assets/840144/15475657/1078fa0c-2103-11e6-9276-5c65bf18216a.jpg)

Be grateful if anyone has any ideas on how I can get this to work as I'd like with both screens.

**Comment by aikar** [comment]
I've had this issue for a very long time too. It is very incapacitating to have to move windows to another screen just to screenshot them.

I have both a USB adapter powered display and thunderbolt display, they both have this issue.

But on my linux desktop, there are no issues with normal powered displays. But in mac with TB/USB, none can be reliably screenshotted (The signal changes every time)

**Comment by aikar** [comment]
Also to note that this has happened with like the past 2-3 major mac OS updates.

**Comment by changeableface** [comment]
Worth mentioning this was with ScreenCloud v1.2.0.

I've checked in recently to find v1.3.0 hoping this would solve the issue, still the same problem.
