### ISSUE TITLE
Dual screen screenshots

### ISSUE THREAD

**Issue by Jona123** [olav-st/screencloud#213]
Hello,

I'm currently on windows 10, and I was wondering: isn't it possible to take a screenshot of both of my screens? I scrolled through the other issues and noticed other people could do that, but I assume that's because ScreenCloud doesn't seem to "support" windows 10. 

Jona

**Comment by magicvince** [comment]
Same problem with 1.5.0 with debian 9 (LMDE) : the -f parameter take the active monitor but not the full screen.  The shooting monitor is the one under the mouse.
