### ISSUE TITLE
Upstart issues with new version

### ISSUE THREAD

**Issue by forteller** [olav-st/screencloud#217]
Hey, I'm really glad to see a new version of SC out! :D 

But I'm having this strange issue with starting the program now.

When I first tried, right after updating (I removed the 15.10 repo and added the 16.04 repo, but did not uninstall/reinstall) starting it from the system menu it did not start, I only got this error message:
![screenshot from 2016-08-14 19-20-45](https://cloud.githubusercontent.com/assets/343561/17662768/57f370d4-62e8-11e6-9e59-49843e866313.png)

But starting it from terminal worked fine.

Well when I turned my pc on this morning SC did not start up automatically as it has always done before. But now I can start it from the menu with no error message! I checked that the settings still says that it should start on boot, and I checked the list of startup applications on my system. Then I rebooted, just to check, but it still did not start automatically (but again I could start it from the system menu without any apparent issues)

PS: this is what it says in my startup applications system (I have not added this manually, it's what was added when I turned on Run on startup in the SC preferences, IIRC):
![screenshot from 2016-08-15 13-17-27](https://cloud.githubusercontent.com/assets/343561/17663170/ce0df774-62ea-11e6-9393-a49d3a56112d.png)

**Comment by olav-st** [comment]
Try turning off "Run on startup", quitting the app, and turning it back on again. That way the .desktop file will be removed and replaced with a new one. The `/opt/screencloud` part is from the older versions and shouldn't be there anymore.

**Comment by forteller** [comment]
Thanks! I tried that. It changed the command in the Startup Apps settings to /usr/bin/screencloud-1.3.0.sh, but it still does not start on boot.

**Comment by ildella** [comment]
Here too, ubuntu 16.04, screencloud at some point last month stopped starting up. No errors, just does not start.
The checkbox is active both in Screencloud preferences and in the Ubuntu Startup Applications Preferences. 

any log I can send to help?

**Comment by ildella** [comment]
Here too, ubuntu 16.04, screencloud at some point last month stopped starting up. No errors, just does not start.
The checkbox is active both in Screencloud preferences and in the Ubuntu Startup Applications Preferences. 
I am sure it was working when I first installed it a few months ago, and did stop working in the last month. 

any log I can send to help?

**Comment by coffeverton** [comment]
I did the same as @ildella , but instead of **/usr/bin/screencloud-1.3.0.sh**, i changed it to **/usr/bin/screencloud**, and now it starts on boot.

**Comment by ildella** [comment]
thanks @coffeverton that worked.
