### ISSUE TITLE
Error to install, dependency libpythonqt-qt5 not found - Ubuntu 16.04

### ISSUE THREAD

**Issue by ma1onso** [olav-st/screencloud#218]
`amarok@amarok-G550JK:~/Downloads$ sudo dpkg -i screencloud_1.3.0-1qt5_amd64.deb 
Selecting previously unselected package screencloud.
(Reading database ... 271750 files and directories currently installed.)
Preparing to unpack screencloud_1.3.0-1qt5_amd64.deb ...
Unpacking screencloud (1.3.0-1qt5) ...
dpkg: dependency problems prevent configuration of screencloud:
 screencloud depends on libpythonqt-qt5; however:
  Package libpythonqt-qt5 is not installed.

dpkg: error processing package screencloud (--install):
 dependency problems - leaving unconfigured
Processing triggers for bamfdaemon (0.5.3~bzr0+16.04.20160701-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for gnome-menus (3.13.3-6ubuntu3.1) ...
Processing triggers for desktop-file-utils (0.22-1ubuntu5) ...
Processing triggers for mime-support (3.59ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.15-0ubuntu1) ...
Errors were encountered while processing:
 screencloud
`

**Comment by olav-st** [comment]
Download libpythonqt-qt5 here: https://build.opensuse.org/package/binaries/home:olav-st/pythonqt-qt5?repository=xUbuntu_16.04

Or just add my repo and apt-get will install it automatically :)

**Comment by MyTheValentinus** [comment]
Hello, i have same error with your repo.

Do you have solution ?

**Comment by MyTheValentinus** [comment]
`valentin@valenitn-factorfx:~/Downloads$ sudo apt install screencloud
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
The following additional packages will be installed:
  libpythonqt-qt5
Les NOUVEAUX paquets suivants seront installés :
  libpythonqt-qt5 screencloud
0 mis à jour, 2 nouvellement installés, 0 à enlever et 0 non mis à jour.
Il est nécessaire de prendre 0 o/3 729 ko dans les archives.
Après cette opération, 21,6 Mo d'espace disque supplémentaires seront utilisés.
Souhaitez-vous continuer ? [O/n] o
(Lecture de la base de données... 212342 fichiers et répertoires déjà installés.)
Préparation du dépaquetage de .../libpythonqt-qt5_3.0-1_amd64.deb ...
Dépaquetage de libpythonqt-qt5 (3.0-1) ...
dpkg: erreur de traitement de l'archive /var/cache/apt/archives/libpythonqt-qt5_3.0-1_amd64.deb (--unpack) :
 tentative de remplacement de « /usr/lib/libPythonQt.so », qui appartient aussi au paquet libpythonqt-dev 3.0-1
Sélection du paquet screencloud précédemment désélectionné.
Préparation du dépaquetage de .../screencloud_1.3.0-1qt5_amd64.deb ...
Dépaquetage de screencloud (1.3.0-1qt5) ...
Traitement des actions différées (« triggers ») pour libc-bin (2.23-0ubuntu3) ...
Traitement des actions différées (« triggers ») pour bamfdaemon (0.5.3~bzr0+16.04.20160701-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Traitement des actions différées (« triggers ») pour gnome-menus (3.13.3-6ubuntu3.1) ...
Traitement des actions différées (« triggers ») pour desktop-file-utils (0.22-1ubuntu5+elementary2~ubuntu0.4.1) ...
Traitement des actions différées (« triggers ») pour mime-support (3.59ubuntu1) ...
Traitement des actions différées (« triggers ») pour hicolor-icon-theme (0.15-0ubuntu1) ...
Des erreurs ont été rencontrées pendant l'exécution :
 /var/cache/apt/archives/libpythonqt-qt5_3.0-1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
`

**Comment by olav-st** [comment]
Do you have any other versions of pythonqt installed?

**Comment by MyTheValentinus** [comment]
Yes version 4. But work before update of this day.

**Comment by n1k0** [comment]
For the records I managed to install and run 1.3 by following the instructions for Ubuntu 16.04 there http://software.opensuse.org/download.html?project=home%3Aolav-st&package=screencloud

**Comment by ErmanSayin** [comment]
@n1k0 That worked for me, thanks!

**Comment by alons45** [comment]
Thanks :dancer: @olav-st

**Comment by matthewdias** [comment]
I can't install libpythonqt-qt5 or screencloud from the repo, they aren't being found. In fact the repo seems to be down, visiting in the browser gives a 404.
