### ISSUE TITLE
Name files with {rnd_s}

### ISSUE THREAD

**Issue by FailPlayDE** [olav-st/screencloud#219]
I installed the last update today and since then all the filenames generated with {rnd_s} look like b'randomstring'.png for example b'fVljnmlt'.png.

![b fvljnmlt](https://cloud.githubusercontent.com/assets/19933721/17678889/52ff6316-6339-11e6-9bac-030c646acbd7.png)

Would be nice if you could fix it, because it looks strange :)

**Comment by dequeues** [comment]
It is because Python 3 returns bytes rather than the encoded string.
