### ISSUE TITLE
The website and pomf.se

### ISSUE THREAD

**Issue by adrian20038** [olav-st/screencloud#22]
Hi! I really like this program, but there is one thing that I would ask you to change on your website. When you take a screenshot and open the link, you immediately see a quite "bloated" page. Could you please just make it spit out the link to the picture source, with only the picture and nothing else?

It would also be really awesome if you could add support to upload to pomf.se (http://pomf.se)

-adrian20038

**Comment by olav-st** [comment]
Closing in favor of https://github.com/olav-st/screencloud/issues/47.
