### ISSUE TITLE
New version 1.3 won't start

### ISSUE THREAD

**Issue by jfreak53** [olav-st/screencloud#221]
I just updated repos to the newest version 1.3 using these instructions:
https://software.opensuse.org/download.html?project=home%3Aolav-st&package=screencloud

I'm on Ubuntu 14.04.5. When I start screencloud I get this error:

```
screencloud: error while loading shared libraries: libquazip.so.1: cannot open shared object file: No such file or directory
```

LS:

```
$ ls /usr/lib/i386-linux-gnu/libquazip.so*
/usr/lib/i386-linux-gnu/libquazip.so.0  /usr/lib/i386-linux-gnu/libquazip.so.0.6  /usr/lib/i386-linux-gnu/libquazip.so.0.6.2
```

**Comment by n1k0** [comment]
Neither won't start on 16.04 64 though with a different error:

```
$ screencloud   
screencloud: error while loading shared libraries: libPythonQt.so.2.1: cannot open shared object file: No such file or directory
```

**Comment by n1k0** [comment]
Trying to install the .deb on 16.04:

```
sudo dpkg -i ~/Downloads/screencloud_1.3.0-1qt5_amd64.deb
Selecting previously unselected package screencloud.
(Reading database ... 294881 files and directories currently installed.)
Preparing to unpack .../screencloud_1.3.0-1qt5_amd64.deb ...
Unpacking screencloud (1.3.0-1qt5) ...
dpkg: dependency problems prevent configuration of screencloud:
 screencloud depends on libqt5concurrent5; however:
  Package libqt5concurrent5 is not installed.
 screencloud depends on libqt5designer5; however:
  Package libqt5designer5 is not installed.
 screencloud depends on libqt5multimedia5-plugins; however:
  Package libqt5multimedia5-plugins is not installed.
 screencloud depends on libquazip5-1 | libquazip-qt5-1 | libquazip-qt5; however:
  Package libquazip5-1 is not installed.
  Package libquazip-qt5-1 is not installed.
  Package libquazip-qt5 is not installed.
 screencloud depends on libpythonqt-qt5; however:
  Package libpythonqt-qt5 is not installed.

dpkg: error processing package screencloud (--install):
 dependency problems - leaving unconfigured
Processing triggers for bamfdaemon (0.5.3~bzr0+16.04.20160701-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for gnome-menus (3.13.3-6ubuntu3.1) ...
Processing triggers for desktop-file-utils (0.22-1ubuntu5) ...
Processing triggers for mime-support (3.59ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.15-0ubuntu1) ...
Errors were encountered while processing:
 screencloud
```

**Comment by olav-st** [comment]
See https://github.com/olav-st/screencloud/issues/218

**Comment by jfreak53** [comment]
I've already got that lib installed:

```
$ sudo apt-get install libpythonqt-qt5
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libpythonqt-qt5 is already the newest version.
```

**Comment by n1k0** [comment]
@olav-st thanks that solved it

**Comment by olav-st** [comment]
@jfreak53 If you're using 14.04 you shouldn't need the qt5 version.

**Comment by jfreak53** [comment]
Yes I am using 14.04. I've tried with and without qt5, same error every time, it will not start.

I had a previous version running just fine, when I started my computer this morning SC told me there was a new version. So I updated my repo and updated SC and that's when it stopped working.

**Comment by jfreak53** [comment]
I've tried many different things, even sym linking the lib file and then downloading the package file and manually installing, still won't run. Please help as I have been without a screen capture program all day since I upgraded. Any way to downgrade?

**Comment by olav-st** [comment]
Older versions are mirrored here if you need to downgrade: 
https://sourceforge.net/projects/screencloud/files/

**Comment by jfreak53** [comment]
Thank you, I downgraded temporarily to 1.2 till this can be fixed. Thanks!

**Comment by Josephvb10** [comment]
I have the same issue:

> screencloud: error while loading shared libraries: libquazip.so.1: cannot open shared object file: No such file or directory

**Comment by zingmars** [comment]
Something is definitely broken in this build. 

I had the same error, and thought I would be clever and fix it by making a symlink to the other libquazip.so file (`sudo ln -s /usr/lib/x86_64-linux-gnu/libquazip.so.0 /usr/lib/x86_64-linux-gnu/libquazip.so.1`), but apparently all the plugins are broken.

`"sni-qt/6443" WARN  14:47:41.184 void StatusNotifierItemFactory::connectToSnw() Invalid interface to SNW_SERVICE 
[WARN] "Error while parsing script file /home/zingmars/.local/share/data/screencloud/ScreenCloud/plugins/imgur/main.py" 
[WARN] "Error while parsing script file /home/zingmars/.local/share/data/screencloud/ScreenCloud/plugins/sftp/main.py" 
[WARN] "Error while parsing script file /home/zingmars/.local/share/data/screencloud/ScreenCloud/plugins/file/main.py" 
[INFO] "Loaded 3 plugin(s)" 
[INFO] "Using bundled icon: :/systray/trayicon-gray.svg" 
[WARN] "Failed to call isConfigured() in SFTPUploader" 
[WARN] "Failed to call isConfigured() in ImgurUploader" 
[WARN] "Failed to call isConfigured() in FileUploader" 
[INFO] "Plugin update check. Has version 1.8 of 'imgur'. Latest is 1.8" 
[INFO] "Plugin update check. Has version 1.6 of 'sftp'. Latest is 1.6" 
[INFO] "Plugin update check. Has version 1.1 of 'file'. Latest is 1.1" 
[INFO] "Plugin update check. Has version 1.8 of 'imgur'. Latest is 1.8" 
[INFO] "Plugin update check. Has version 1.6 of 'sftp'. Latest is 1.6" 
[INFO] "Plugin update check. Has version 1.1 of 'file'. Latest is 1.1" 
Got a buffer underflow! 
[WARN] "Error while playing audio. Code: 3" 
[WARN] "Failed to call showSettingsUI() in ImgurUploader" 
`

**Comment by HWiese1980** [comment]
Has this been solved? I'm experiencing the same issue with the missing `libquazip.so.1`.

**Comment by linuxthefish** [comment]
If you have this issue on Debian Sid, use the http://download.opensuse.org/repositories/home:/olav-st/xUbuntu_16.04/ repo
