### ISSUE TITLE
formatFilename doesn't remove extensions when includeFileExtension argument is False

### ISSUE THREAD

**Issue by dequeues** [olav-st/screencloud#223]
The second argument of formatFileName is `includeFileExtension` but it doesn't actually remove the extension if one is specified.

```
py> print(ScreenCloud.formatFilename("file_name.png"))
file_name.png
py> print(ScreenCloud.formatFilename("file_name.png", False))
file_name.png
```

I'm not sure if file extensions are meant to be passed to that function, but I know that Imgur and FTP plugins do just that.

Off: Is there an IRC channel for ScreenCloud? Could work out, if not.

**Comment by olav-st** [comment]
You're meant to pass the name without the extension, since the extension is taken from QSettings:
```python
py> from PythonQt.QtCore import QSettings
py> settings = QSettings()
py> settings.beginGroup("main")
py> print(settings.value("format"))
png
```
The Imgur and FTP thing might be an oversight. I'll take a look at it when I have time.

> Off: Is there an IRC channel for ScreenCloud? Could work out, if not.

Not at the moment. Is there an easy way to set one up? I could do it if people would use it :)

**Comment by dequeues** [comment]
Yeah, I wasn't sure if it was a plugin issue or a core issue. I was modifying the FTP plugin to remove extensions (with a UI addition) when copying to clipboard when I came across this. I could probably sort those if you're busy, though.

About IRC: http://freenode.net/news/registering-a-channel-on-freenode
