### ISSUE TITLE
STFP not working?

### ISSUE THREAD

**Issue by dnlxh** [olav-st/screencloud#226]
Hey, since I updated to 1.3 I'm not able to upload anything to my own server via SFTP.

I already clean installed. (Deinstalled, deleted roaming/Local folder)

That's what I get. 

![1](https://cloud.githubusercontent.com/assets/14241290/17748018/be845f0e-64b7-11e6-9ae4-7027ae94ceb4.JPG)

**Comment by MyTheValentinus** [comment]
SAME issue.

**Comment by vinise** [comment]
Same issue!
Is it possible to get a link to 1.2 version while fixing  this bug?
This is really annoying

**Comment by olav-st** [comment]
Older versions are mirrored here if you need to downgrade: 
https://sourceforge.net/projects/screencloud/files/

**Comment by vinise** [comment]
Thanks for this :)

Looking forward having 1.3 working with sftp ! great work until now ocntinue :)

**Comment by Hugo1380** [comment]
Same issue on Ubuntu 16.04 and older versions don't work :/

**Comment by deanpcmad** [comment]
Same here on Ubuntu 16.04:

```
Error in file: /home/dean/.local/share/screencloud/ScreenCloud/plugins/sftp/main.py
Traceback (most recent call last):
  File "<string>", line 5, in <module>
  File "/home/dean/.local/share/screencloud/ScreenCloud/plugins/sftp/modules/paramiko/__init__.py", line 30, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "/home/dean/.local/share/screencloud/ScreenCloud/plugins/sftp/modules/paramiko/transport.py", line 50, in <module>
    from paramiko.dsskey import DSSKey
  File "/home/dean/.local/share/screencloud/ScreenCloud/plugins/sftp/modules/paramiko/dsskey.py", line 26, in <module>
    from Crypto.PublicKey import DSA
ImportError: No module named Crypto.PublicKey
```

and

```
Failed to call SFTPUploader.showSettingsUI()
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name SFTPUploader
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'SFTPUploader' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'sftp_u' is not defined
```

**Comment by jflory7** [comment]
I receive the same problem as @deanpcmad on Fedora 24 (`kernel.4.6.6-300.fc24.x86_64`).

@olav-st Any kind of ETA on if this fix is something that would come soon (not sure if this is a complicated problem or an easyfix). Just trying to figure out if I should bother downgrading for a while or just waiting for a stable fix.

**Comment by MyTheValentinus** [comment]
For temp fix, if you want: copy Crypto librairie in modules folder of sftp plugin.

**Comment by jflory7** [comment]
@MyTheValentinus When you say copy the crypto library, what are you talking about, OpenSSL? How did you place this into `modules/`? I found the location you're referring to (`~/.local/share/data/screencloud/ScreenCloud/plugins/sftp/modules/`), but I'm not sure what to do here.

**Comment by MyTheValentinus** [comment]
Hello @jflory7,
`~/.local/share/screencloud/ScreenCloud/plugins/sftp/modules/Crypto`  for me and work

![08 09 16-10-26-08](https://cloud.githubusercontent.com/assets/6104498/18342347/b9d2caba-75ae-11e6-96a4-9ac7b623f380.png)

**Comment by zingmars** [comment]
@MyTheValentinus Which crypto library are you referring to? Full name please.

**Comment by AmauryCarrade** [comment]
I solved this by installing `pycrypto` from PIP:
```bash
sudo pip install pycrypto
```
and then linking the library in the `modules` folder, following @MyTheValentinus advice (you may have to change the `Crypto` directory location according to your system).
```
cd ~/.local/share/screencloud/ScreenCloud/plugins/sftp/modules
ln -s /usr/lib/python3.5/site-packages/Crypto/ Crypto
```

**Comment by Samaru** [comment]
Same. Pretty sure this must just be 1.3 then. I get this on windows. I completely deleted every trace and it still happens. Why haven't they noticed this, there must be LOADS of people using SFTP.

**Comment by harkor** [comment]
Not working for me, still the same error
http://screen.harkor.sexy/Screenshot_09-15-17.png

I don't have Crypto for python 3.5 like AmauryCarrade

I stay on ScreenCloud 1.2 for now...

**Comment by vinise** [comment]
same for me on windows... not working.  
a bit sad 3 month passed and still not fixed 😢

**Comment by populov** [comment]
One year passed, still not fixed. I have to use v1.2 both on Linux and windows.
Maybe someone has fork, where SFTP is fixed?

**Comment by zingmars** [comment]
@populov Try ShareX on Windows. It's pretty decent. 

As for Linux, you can try the temporary fix mentioned in https://github.com/olav-st/screencloud/issues/226#issuecomment-246120108, or by writing a quick bash script to upload using scp and then using selecting it in the upload directory.

**Comment by populov** [comment]
@zingmars thanks, temporary fix can work for me personally, but I need a same solution for 200 people across several international offices on Mac, Windows and Linux to work with corporate SFTP server. Not all of them are technical. I can create a manual 'Download installer from here and enter your credentials and these parameters there'. And I can set link to download v1.2 instead of v1.3. But I don't want to explain, for example, to new HR or office manager girl, that she must install a missing python package via pip and create symlink in a hidden folder.

ShareX doesn't fit, as it's Windows only, and I didn't find SFTP support there.

**Comment by zingmars** [comment]
@populov In ShareX, SFTP is an option in the FTP uploader. But yes, it's a Windows-only option.

Another alternative for screencloud would be taking v1.3, manually fixing the problem and then [repackaging the app](https://github.com/olav-st/screencloud/tree/master/deploy). Then you can either deploy it through whatever deployment system your company has.

**Comment by EusebiuOprinoiu** [comment]
Any new updates regarding this issue?
It's been almost 2 years and SFTP is still broken in the latest version of ScreenCloud.

**Comment by zingmars** [comment]
Looking at how the last commits were pretty much just the dev deprecating his image hosting site, it's safe to say that this project was abandoned. Your best bet is trying the fix mentioned above or looking for an alternative.

**Comment by EusebiuOprinoiu** [comment]
That's just sad! This used to be one of my favorite apps.

**Comment by alexhotoi** [comment]
Hello,

I am using ScreenCloud on Kubuntu 18.04 LTS.

I managed to resolve this issue with ScreenCloud 1.3.0 version.

Navigate to this file :

~/.local/share/screencloud/ScreenCloud/plugins/sftp/modules/paramiko

Search for "CTR" and check for this line :
return self._cipher_info[name]['class'].new(key, self._cipher_info[name]['mode'], iv, counter)

Replace the parameter "iv" with an empty string as below :

        elif name.endswith("-ctr"):
            # CTR modes, we need a counter
            counter = Counter.new(nbits=self._cipher_info[name]['block-size'] * 8, initial_value=util.inflate_long(iv, True))
            return self._cipher_info[name]['class'].new(key, self._cipher_info[name]['mode'], '', counter)
            #return self._cipher_info[name]['class'].new(key, self._cipher_info[name]['mode'], iv, counter)
        else:
            return self._cipher_info[name]['class'].new(key, self._cipher_info[name]['mode'], iv)

BR/ Alex

**Comment by Tassleh0ff** [comment]
Does anyone know where to find this transport.py file on Windows or any other workaround for this problem?

Thanks

**Comment by nrylov1** [comment]
> Does anyone know where to find this transport.py file on Windows or any other workaround for this problem?
> 
> Thanks

Personally I just use the previous version and disabled update checker, works fine

**Comment by pitkes22** [comment]
All I have to do to fix this issue was to install `ssh2-python` with `pip install ssh2-python`

**Comment by leo-mao** [comment]
dito, this messed my python env up though
