### ISSUE TITLE
Screencloud wont work in windows with update 1.3.0

### ISSUE THREAD

**Issue by sakurazaki** [olav-st/screencloud#227]
Hi,

I recently updated Screencloud to 1.3.0 and right after installing it it just wont work, even if I reinstall it.
I tried using Dropbox and Screencloud. Dropbox doesnt even let me configure it and Screencloud wont upload.
See attached screenshots:

My system is Windows 10 x64

![captura](https://cloud.githubusercontent.com/assets/191530/17776080/5c532c08-655b-11e6-8a0c-7c52c44b0d76.PNG)
![captura2](https://cloud.githubusercontent.com/assets/191530/17776081/5c5545d8-655b-11e6-99c2-704f6665f382.PNG)

**Comment by jheidt** [comment]
Most likely a related issue:
![error message](http://i.imgur.com/33koBUA.png)

**Comment by matthijs186** [comment]
Can confirm the same errors error dialog(s) as @jheidt with the **imgur** plugin.

Windows 10 Build 14393
ScreenCloud 1.3.0

After updating ScreenCloud and installing the imgur plugin I get the following errors.

After download
![Errors after install](http://i.imgur.com/RIOjTd8.jpg)

After the previous dialog
![More errors after install](http://i.imgur.com/zp4ONAw.jpg)

Attempting to change plugin settings
![Errors attempting to change settings](http://i.imgur.com/Q1z0qdD.jpg)

**Comment by olav-st** [comment]
See https://github.com/olav-st/screencloud/issues/225
