### ISSUE TITLE
Region capture selection tool very slow after update

### ISSUE THREAD

**Issue by jjnilton** [olav-st/screencloud#228]
Capture selection tool got [very slow](https://gfycat.com/LiveIckyFawn) after update, can't select a region a region properly.

I removed the previous repository from sources (15.10), added the new one (16.04) and reinstalled ScreenCloud, but still getting the same issue.

No strange output when running from terminal:

> $ screencloud
> [INFO] "Loaded 0 plugin(s)"
> [INFO] "Using bundled icon: :/systray/trayicon-gray.svg"
> [INFO] "Unloaded 0 plugin(s)"

[Screencast_18-08-16_11:52:02.webm.zip](https://github.com/olav-st/screencloud/files/425231/Screencast_18-08-16_11.52.02.webm.zip)

Screencloud version: 1.3.0
Ubuntu GNOME 16.04

**Comment by Hugo1380** [comment]
Same on Ubuntu Unity 16.04

**Comment by MyTheValentinus** [comment]
Same on Elementary OS based on Ubuntu 16.04

**Comment by MariusJS** [comment]
Same on Ubuntu Gnome 16.04.01

**Comment by NerdmindDE** [comment]
Hi. I've exactly the same problem on Ubuntu 16.04.1 LTS [_Gnome Compiz_] with Screencloud 1.3.0.

**Comment by MariusJS** [comment]
Reinstalled to 16.10, and now it works as it should.

**Comment by LangdalP** [comment]
I got the same problem on Linux Mint 18. Taking large screenshots with the region tool takes forever, as I have to wait for the box to get larger.

**Comment by MyTheValentinus** [comment]
Up ? Same on Ubuntu 16.04

**Comment by Jonni1** [comment]
Still hasn't been fixed.

**Comment by MariusJS** [comment]
Have you that still has the problem tried going to 16.10 and/or clean 16.04?

I can report that it works fine in 17.04 aswell.

**Comment by theonedemon** [comment]
Up, same problem on Xubuntu 16.04

**Comment by nikopolidi** [comment]
+1 osing Xubuntu 16.04
Capturing area is moving toooo sloooow while selecting area.

**Comment by MyTheValentinus** [comment]
Up ?

**Comment by mdobrenko** [comment]
Same problem, using Linux Mint 18.

**Comment by alextpedro** [comment]
Same problem, Linux Mint 18.1, freshly installed.

**Comment by jac1013** [comment]
Same situation, Linux Mint 18.1

**Comment by misnor** [comment]
This issue is still occurring on Elementary OS as of March 25th, any progress or indication that this is going to be be resolved?

**Comment by Nerdmind** [comment]
Hi again. I just noticed that the region caputure selection does not lag anymore (**Ubuntu 16.04 LTS**). I use Screencloud (1.3.0) each day and have looked into the `history.log` of APT to see what was recently upgraded. I think that one of the following upgrades is responsible for that the problem has gone(?):

	libqt5test5:amd64 (5.5.1+dfsg-16ubuntu7.2, 5.5.1+dfsg-16ubuntu7.5),
	libqt5dbus5:amd64 (5.5.1+dfsg-16ubuntu7.2, 5.5.1+dfsg-16ubuntu7.5),
	libqt5sql5-sqlite:amd64 (5.5.1+dfsg-16ubuntu7.2, 5.5.1+dfsg-16ubuntu7.5),
	libqt5widgets5:amd64 (5.5.1+dfsg-16ubuntu7.2, 5.5.1+dfsg-16ubuntu7.5),
	libqt5xml5:amd64 (5.5.1+dfsg-16ubuntu7.2, 5.5.1+dfsg-16ubuntu7.5),
	libqt5printsupport5:amd64 (5.5.1+dfsg-16ubuntu7.2, 5.5.1+dfsg-16ubuntu7.5),
	libqt5concurrent5:amd64 (5.5.1+dfsg-16ubuntu7.2, 5.5.1+dfsg-16ubuntu7.5),
	libqt5gui5:amd64 (5.5.1+dfsg-16ubuntu7.2, 5.5.1+dfsg-16ubuntu7.5),
	libqt5core5a:amd64 (5.5.1+dfsg-16ubuntu7.2, 5.5.1+dfsg-16ubuntu7.5),
	libqt5libqgtk2:amd64 (5.5.1+dfsg-16ubuntu7.2, 5.5.1+dfsg-16ubuntu7.5),
	libqt5opengl5:amd64 (5.5.1+dfsg-16ubuntu7.2, 5.5.1+dfsg-16ubuntu7.5),
	libqt5network5:amd64 (5.5.1+dfsg-16ubuntu7.2, 5.5.1+dfsg-16ubuntu7.5),
	libqt5sql5:amd64 (5.5.1+dfsg-16ubuntu7.2, 5.5.1+dfsg-16ubuntu7.5)
