### ISSUE TITLE
SFTP is broken

### ISSUE THREAD

**Issue by ghost** [olav-st/screencloud#23]
No matter what I try. Screencloud always fails to establish an SFTP session. I checked with wireshark and it doesn't even open a TCP connection.

Tried it on two machines with complete different software configurations and checked all configs a hundred times.

OS: Windows XP and Win 7 (64bit)
Version: 1.1.0

**Comment by Nek-** [comment]
@olav-st any plan to update the ubuntu repository ? ^^ http://download.opensuse.org/repositories/home:/olav-st/xUbuntu_16.04/
