### ISSUE TITLE
Chrome Canary (54.0.2835.0): screencloud.net uses an unsupported protocol.

### ISSUE THREAD

**Issue by EdwardRech** [olav-st/screencloud#231]
This site can’t provide a secure connection

screencloud.net uses an unsupported protocol.
ERR_SSL_OBSOLETE_CIPHER

Unsupported protocol
The client and server don't support a common SSL protocol version or cipher suite.

^^^ that is what chrome says. I attached a screenshot just in case.

Please fix it. http://i.imgur.com/0uFmFer.png

**Comment by olav-st** [comment]
I've added some newer ciphers to the config. Does it work now?

**Comment by EdwardRech** [comment]
Nope, sadly still doesn't work.

http://i.imgur.com/uK6rbCe.png

(ERR_SSL_VERSION_OR_CIPHER_MISMATCH)

**Comment by Xseba360** [comment]
I can confirm it also happens to me 
![screenshot](http://i.imgur.com/XLDLL3u.png)

**Comment by olav-st** [comment]
Works for me in Chrome now, can anyone confirm?

**Comment by Xseba360** [comment]
After clearning all cache/cookies/data I still get the ERR_SSL_OBSOLETE_CIPHER error in Chrome Canary. Works fine in Firefox Dev Edition though. I don't believe this is a Chrome bug because other websites work fine in it. Maybe the server software is outdated (nginx, openssl etc.?)

**Comment by Xseba360** [comment]
from Chrome Stable console:
`This site requires a DHE-based SSL cipher suite. These are deprecated and will be removed in M52, around July 2016. See https://www.chromestatus.com/feature/5752033759985664 for more details.`

**Comment by EdwardRech** [comment]
Can confirm what Xseba360 said.

**Comment by e-M-c-E** [comment]
That same error is on Chrome 53.0.2785.89 beta-m (64-bit) in Win10.
In Linux Mint mate x64 (also in latest Chrome beta) works ok.

**Comment by QuiZr** [comment]
Same here: 32 bit 53.0.2785.89m on Win10.

**Comment by e-M-c-E** [comment]
Update:
Since today's Chrome on Linux Mint update to 53.0.2785.92 beta (64-bit) vresion, the issue appear here also.
"ERR_SSL_OBSOLETE_CIPHER" - unsupported protocol.
The Firefox 48.0 open the page without any problems.

**Comment by urbels** [comment]
Same for me 53.0.2785.92 (64-bit) Chrome Linux

**Comment by olav-st** [comment]
I've tweaked the server settings and it works for me now (Chrome 53.0.2785.92). Does it work for anyone else?

**Comment by e-M-c-E** [comment]
@olav-st 
Super! Works now for me to.. on Chrome 53.0.2785.92 beta (64-bit) linux.
:)

**Comment by urbels** [comment]
Works for me too, Thanks!

**Comment by EdwardRech** [comment]
Can confirm it's fixed for me too, thanks!

**Comment by pacoalias** [comment]
@olav-st please, can you share what you did on server-side ? I'm curious about the final solution that worked. Thanks.
