### ISSUE TITLE
Error on startup with any plugin: ImportError: No module named ScreenCloud

### ISSUE THREAD

**Issue by neodc** [olav-st/screencloud#232]
1.3 on ubuntu 14.04, when I start screencloud with any plugin activated (here sftp) I get the error :

```
Error in file: /home/neodc/.local/share/data/screencloud/ScreenCloud/plugins/sftp/main.py
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named ScreenCloud
```

And if I try to open its configuration I get :

```
Failed to call SFTPUploader.showSettingsUI()
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name SFTPUploader
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'SFTPUploader' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'sftp_u' is not defined
```

**Comment by core01** [comment]
Same error Ubuntu 16.04

**Comment by mrStiher** [comment]
Same error elementary OS 0.3.2 Freya (Ubuntu 14.04)

**Comment by hunterforcode** [comment]
the same error on Linux Mint 17.2

**Comment by FromCrimsonToWool** [comment]
olav-st, I was able to resolve this on Korora 24( Fedora 24 ) by adding the following lines to the top of ~/.local/share/data/screencloud/ScreenCloud/plugins/ftp/main.py
**`import sys`
`sys.path.insert(1, '{project_path}')`**

Then I just needed to run:
**`sudo ln -s /usr/include/python2.7 /usr/local/include/python2.7`**

Hope that helps someone.

**Comment by simgislab** [comment]
I've tried above. There is no 'No module named ScreenCloud' anymore, but the following occurs on starting ScreenCloud:

>Error in file: /home/sim/.local/share/data/screencloud/ScreenCloud/plugins/ftp/main.py
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/usr/share/screencloud/modules/ScreenCloud.py", line 1, in <module>
    from PythonQt.QtCore import QSettings
ImportError: cannot import name QSettings

ScreenCloud actually starts after that, but attempt to open FTP settings produces:

>Failed to call FTPUploader.showSettingsUI()
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'ftp_u' is not defined

**Comment by FromCrimsonToWool** [comment]
@simgislab, looks like this may be another issue related to #221

**Comment by FromCrimsonToWool** [comment]
@simgislab It would appear that some of the required libraries for Screencloud to install are not available on Ubuntu 14.04 as show here:  http://screencloud.net/v/whv0  Not sure if @olav-st would address that or not, but that's what I was able to find thus far.

**Comment by SkyzohKey** [comment]
same on Fedora 23 since 0.1.3 update :/

**Comment by NoahWilcox** [comment]
Same issue here on Arch.
