### ISSUE TITLE
Window capture problems

### ISSUE THREAD

**Issue by p-boiko** [olav-st/screencloud#234]
Here is an XFCE-Terminal screenshot: http://screencloud.net/v/36F1
Now Thunar screenshot: http://screencloud.net/v/qUoF (the empty stripe below window, and missing window title bar). Window manager: openbox.
And now the whole screen shot for reference: http://screencloud.net/v/12Ka
By the way, error message appeared after the last screenshot, though everything seemed to work fine: http://screencloud.net/v/wKkx
And the last one, offtopic: http://screencloud.net/v/pe2q (the popup window shadow doesn't match window's shape. I use Compton for composition manager)

**Comment by WebShapedBiz** [comment]
I'm also having similar problems with Window capture and it would be nice if @olav-st actually read our issues. It could save him embarrassment of labelling @p-boiko's issue as "Windows-specific".

**Comment by olav-st** [comment]
@WebShapedBiz Geez man, calm down. I looked at the title and misread "window" as "windows".
 
I tag issues for my own convenience only. It makes it easier to find relevant issues when I'm working on a specific part of the code. That's when I'll read the entire issue.

**Comment by WebShapedBiz** [comment]
Sorry @olav-st if I came across too strong, I was wrongfully presuming your reaction as a sloppy job. Now I know better.

Cheers.
