### ISSUE TITLE
screencloud error the program can't start because api-ms-win-runtime-l1-1-0.dll wasn't found

### ISSUE THREAD

**Issue by mescalito** [olav-st/screencloud#237]
Hi! I got that error after installing the latest version 

> program can't start because api-ms-win-runtime-l1-1-0.dll wasn't found

I use Windows 7.

I fixed the error after finding this video: https://www.youtube.com/watch?v=18-NocobSQk

I downloaded and had to install this library from Microsoft
http://download.microsoft.com/download/8/c/b/8cb4af84-165e-4b36-978d-e867e07fc707/vc_redist.x64.exe

Good luck!

**Comment by olav-st** [comment]
Closing this since you figured it out. The issue will still be searchable in case anyone else runs into the same problem :)
