### ISSUE TITLE
Q: Free account limited storage time

### ISSUE THREAD

**Issue by WebShapedBiz** [olav-st/screencloud#238]
Hi.

There is no information on your website about how long is the limited storage time for Free accounts. It just mention `ScreenCloud.net offers free temporary hosting of your screenshots.`

Thank you for your time and effort in putting together this app.

Cheers.

**Comment by WebShapedBiz** [comment]
Bump.

**Comment by olav-st** [comment]
I believe it's 2 months at the moment, but I'd rather not mention a specific number on the website. The number changes over time depending on how much storage I have and how many people are subscribing to the paid service, etc.

Ideally there should be a visual indicator on the dashboard. I'll look into that when I have time.

**Comment by WebShapedBiz** [comment]
Thank you for your time and effort. Dashboard indicator would be nice although from the business point of view it may be better to leave it as it is.

Cheers.

**Comment by olav-st** [comment]
Closing this since the screenshot hosting service has been shut down.
