### ISSUE TITLE
FTP Plugin error "No module named ScreenCloud"

### ISSUE THREAD

**Issue by ava7** [olav-st/screencloud#240]
There is an issue with version 1.3.0. When trying to install the FTP plugin, the following error pops out:

![screencloud-ftp-error](https://cloud.githubusercontent.com/assets/1859550/18524577/9e48716a-7ac1-11e6-91a4-7c134d995840.png)

```
ava@localhost| ~ $ head -2 /home/ava/.local/share/data/screencloud/ScreenCloud/plugins/ftp/main.py 
import ScreenCloud
from PythonQt.QtCore import QFile, QSettings, QBuffer, QIODevice
```
---
### Steps to reproduce:
1. Start the program
2. Go to Preferences...
3. Click on the "Online Services" tab
4. Click on the "More Services" button
5. Check the "FTP" option and hit the "OK" button
### System information

Fedora 23 KDE - 4.7.2-101.fc23.x86_64
screencloud-1.3.0-21.1.x86_64
Python 2.7.11
## Python 3.4.3

Let me know if any other information is needed
Cheers!

**Comment by neodc** [comment]
Seems like the same issue than me (#232).

**Comment by FromCrimsonToWool** [comment]
Added a possible solution/workaround to https://github.com/olav-st/screencloud/issues/232#issuecomment-253516868

**Comment by ava7** [comment]
@FromCrimsonToWool Thanks, mate, this workaround did work. I will close this issue and wait for a stable fix in #232

**Comment by FromCrimsonToWool** [comment]
ava7, I'm super glad I was able to help!

**Comment by FromCrimsonToWool** [comment]
@ava7, I'm super glad I was able to be of assistance!
