### ISSUE TITLE
Failed to call SFTPUploader.upload()

### ISSUE THREAD

**Issue by ghost** [olav-st/screencloud#241]
Just installed 1.3.0 of screencloud and my SFTP configuration is not working but it did in the previous version 1.2.0.
![capture](https://cloud.githubusercontent.com/assets/22616074/19074272/56f83d88-8a37-11e6-8c5b-6bae0177dce7.PNG)

**Comment by SuchYare** [comment]
This issue is happening to me on Xubuntu 16.04, it appears that the author does not have time to actively commit so I would check back in 1-2 months to see if any activity was tracked.

**Comment by walrusEOF** [comment]
Okay thanks for the heads up.

**Comment by jeserkin** [comment]
Jep. Does not work. What is with this application. Is it supported/developed or dead?

**Comment by olav-st** [comment]
I maintain it when I have time, but that's mainly in the holidays. Contributions are therefore very welcome!

**Comment by jeserkin** [comment]
@olav-st any suggestions on where to start? And description for development environment required for it? Build process, etc.

**Comment by olav-st** [comment]
@jeserkin Check out the [wiki](https://github.com/olav-st/screencloud/wiki). There's articles on how to compile the program and an [introduction to writing plugins](https://github.com/olav-st/screencloud/wiki/Plugin-Overview).

**Comment by jeserkin** [comment]
Okay. Will do. Thank you.

**Comment by Athyk** [comment]
Issue is still not fixed, maybe add the hacktoberfest label here?

**Comment by EusebiuOprinoiu** [comment]
Any new updates about this issue? It's been more than 2 years since the SFTP plugin stopped working.
Both 1.3.0 and 1.4.0 versions are broken on Windows 10.

**Comment by olav-st** [comment]
As I've stated before, I'm not actively developing ScreenCloud anymore. I try to work on it whenever I have some free time, but this issue would probably require a new Windows-release and that usually takes me at least a few days. This is unfortunate and I would like to automate the process like I've done for Mac and Linux, but Travis doesn't support Windows yet. 

So don't expect a fix anytime soon unless someone volunteers their time to debug and patch this.
