### ISSUE TITLE
Screenshot to gif

### ISSUE THREAD

**Issue by kubahaha** [olav-st/screencloud#244]
It would be nice enhancement if we could make animated screenshot to gif

**Comment by thenamelessthing** [comment]
I'm interested too!

**Comment by rikai** [comment]
Agreed, this is the #1 feature I miss from other screenshotting utilities and would get me 95% of the way to dumping other things entirely in favor of screencloud

**Comment by olav-st** [comment]
Closing as a duplocate of https://github.com/olav-st/screencloud/issues/112
