### ISSUE TITLE
Incorrect scaling on high DPI displays

### ISSUE THREAD

**Issue by Xyene** [olav-st/screencloud#245]
I have a 4K (3840 x 2160) display, and am running screencloud on Windows 10. It mainly works, but the text that provides a help message uses a much larger font than is necessary to display at this resolution.

![image](https://cloud.githubusercontent.com/assets/1403503/19784688/acd2fde4-9c64-11e6-8f2d-f555b116a9bd.png)

It would appear the issue is Windows' app scaling feature, where it comes preset at 250% scaling on my laptop, and handles scaling by itself. When I set it back down to 100% the text displays properly (though the rest of Windows is unusably small).

I noticed a similar issue, though less pronounced, on a 1080p display &mdash; perhaps something could be done to disable text scaling on Windows machines? The OS handles it well in other applications, so I assume it's something specific to screencloud.

**Comment by sandra1n** [comment]
Same issue
on 4k some windows are small

**Comment by freecod** [comment]
Fix scaling bug (tested on linux) - set environment parameter QT_SCREEN_SCALE_FACTORS=1 before run ScreenCloud

> QT_SCREEN_SCALE_FACTORS=1 screencloud

Info for developer:
https://doc.qt.io/qt-5/highdpi.html
