### ISSUE TITLE
Feature request: edit on screenshot

### ISSUE THREAD

**Issue by aistis-** [olav-st/screencloud#248]
Hi guys, I am using screencloud and it is an awesome app for screenshots.

BUT! I am really missing feature to edit screenshot like highlighting some important details or adding text comment.

**Comment by olav-st** [comment]
This is already implemented. Click on the thumbnail in the save dialog to edit.

**Comment by aistis-** [comment]
Thanks for the quick response! @olav-st could you be more specific? I cannot find this feature: https://screencloud.net/v/uAl6

**Comment by olav-st** [comment]
Sure, see https://screencloud.net/v/6r0Z

**Comment by aistis-** [comment]
Thank you! Turns out I've disabled this preview window

**Comment by olav-st** [comment]
I see. There should be a way to enable the editor without the preview window, but I haven't found a good way to do it yet. Maybe a custom shortcut when you want to use the editor?
