### ISSUE TITLE
Need visible tray icon for Mac dark menu bar

### ISSUE THREAD

**Issue by KVuncannon** [olav-st/screencloud#252]
Need visible tray icon for Mac dark menu bar.

**Comment by tobiasreinhard** [comment]
+1 Really needed.

**Comment by rikai** [comment]
Yeah, basically impossible to use the menubar icon at the moment if you're using the dark version.

**Comment by tobiasreinhard** [comment]
And i love the dark menubar, it looks so much better than the light one.

**Comment by electronicboy** [comment]
+1 I thought the app was totally broken because of this.

**Comment by Hakuss** [comment]
That empty space... 😞 
![zrzut ekranu 2017-04-06 o 09 58 19](https://cloud.githubusercontent.com/assets/22944204/24743977/a55f1b2c-1ab0-11e7-92f9-fe6342d7135f.png)

**Comment by fharper** [comment]
Oh wow, I'm glad I found this issue as I thought the app wasn't working: I didn't see any icons in the menubar or in the Dock.

**Comment by olav-st** [comment]
Closing as a duplicate of https://github.com/olav-st/screencloud/issues/152, which has now been fixed.
