### ISSUE TITLE
Segfault during module install

### ISSUE THREAD

**Issue by lag-linaro** [olav-st/screencloud#253]
[INFO] "Loaded 0 plugin(s)"
[INFO] "Using bundled icon: :/systray/trayicon-gray.svg"
[INFO] "Checking https://raw.githubusercontent.com/olav-st/screencloud-plugins/master/plugin-list.xml for redirect"
[WARN] "Failed to get version info for plugin 'imgur'. Unable to open /home/lee/.local/share/screencloud/ScreenCloud/plugins/imgur/metadata.xml"
[INFO] "Deleting /home/lee/.local/share/screencloud/ScreenCloud/plugins/dropbox"
[INFO] "Deleting /home/lee/.local/share/screencloud/ScreenCloud/plugins/ftp"
[INFO] "Deleting /home/lee/.local/share/screencloud/ScreenCloud/plugins/sftp"
[INFO] "Deleting /home/lee/.local/share/screencloud/ScreenCloud/plugins/file"
[INFO] "Deleting /home/lee/.local/share/screencloud/ScreenCloud/plugins/shell"
[INFO] "[1/4] Downloading archive for plugin from: https://raw.githubusercontent.com/olav-st/screencloud-plugins/master/imgur/current.zip..."
[INFO] "Checking https://raw.githubusercontent.com/olav-st/screencloud-plugins/master/imgur/current.zip for redirect"
[INFO] "[2/4] File /tmp/current-295hBo.zip downloaded."
[INFO] "[3/4] Exctracting plugin archive /tmp/current-295hBo.zip to /tmp/current-295hBo"
Segmentation fault (core dumped)

**Comment by lag-linaro** [comment]
`strace screencloud` output:

fcntl(35, F_SETFD, FD_CLOEXEC)          = 0
brk(0x2d9a000)                          = 0x2d9a000
brk(0x2d96000)                          = 0x2d96000
mmap(NULL, 266240, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f58b1f79000
brk(0x2d86000)                          = 0x2d86000
mremap(0x7f58b1f79000, 266240, 528384, MREMAP_MAYMOVE) = 0x7f58b1ef8000
mremap(0x7f58b1ef8000, 528384, 1052672, MREMAP_MAYMOVE) = 0x7f58b1df7000
fstat(35, {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
write(35, "PK\3\4\n\0\0\0\0\0\20~\fI\0\0\0\0\0\0\0\0\0\0\0\0\20\0\34\0mo"..., 764079) = 764079
munmap(0x7f58b1df7000, 1052672)         = 0
close(35)                               = 0
write(2, "[INFO] \"[2/4] File /tmp/current-"..., 56[INFO] "[2/4] File /tmp/current-295hBo.zip downloaded."
) = 56
poll([{fd=3, events=POLLIN|POLLOUT}], 1, -1) = 1 ([{fd=3, revents=POLLOUT}])
writev(3, [{iov_base="+\0\1\0", iov_len=4}], 1) = 4
futex(0x7ffd614eacd4, FUTEX_WAIT_PRIVATE, 1, NULL) = 0
futex(0x2724b38, FUTEX_WAKE_PRIVATE, 1) = 0
poll([{fd=3, events=POLLIN|POLLOUT}], 1, -1) = 1 ([{fd=3, revents=POLLOUT}])
writev(3, [{iov_base=";\3\5\0#\0\340\3\0\0\0\0\v\0\37\0\262\0\26\0\202\3\n\0 \0\340\3#\0\340\3"..., iov_len=76}], 1) = 76
mkdir("/tmp/current-295hBo", 0777)      = -1 EEXIST (File exists)
write(2, "[INFO] \"[3/4] Exctracting plugin"..., 89[INFO] "[3/4] Exctracting plugin archive /tmp/current-295hBo.zip to /tmp/current-295hBo"
) = 89
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_ACCERR, si_addr=0x7f58e8409270} ---
+++ killed by SIGSEGV (core dumped) +++
Segmentation fault (core dumped)

**Comment by olav-st** [comment]
This could be caused by a Qt 4/5 mismatch. You might be using the Qt 4 version of QuaZip and the Qt 5 version of everything else or vice versa. What is the output of `ldd /usr/bin/screencloud`?

**Comment by lag-linaro** [comment]
linux-vdso.so.1 (0x00007ffea5547000)
	libQt5Xml.so.5 => /usr/lib/libQt5Xml.so.5 (0x00007f33a8c1d000)
	libQt5Multimedia.so.5 => /usr/lib/libQt5Multimedia.so.5 (0x00007f33a8911000)
	libQt5X11Extras.so.5 => /usr/lib/libQt5X11Extras.so.5 (0x00007f33a870c000)
	libquazip.so.1 => /usr/lib/libquazip.so.1 (0x00007f33a84db000)
	libPythonQt.so.1 => /usr/lib/libPythonQt.so.1 (0x00007f33a802b000)
	libPythonQt_QtAll.so.1 => /usr/lib/libPythonQt_QtAll.so.1 (0x00007f33a6af5000)
	libX11.so.6 => /usr/lib/libX11.so.6 (0x00007f33a67b6000)
	libQt5Widgets.so.5 => /usr/lib/libQt5Widgets.so.5 (0x00007f33a5f5d000)
	libQt5Network.so.5 => /usr/lib/libQt5Network.so.5 (0x00007f33a5bf4000)
	libQt5Gui.so.5 => /usr/lib/libQt5Gui.so.5 (0x00007f33a54b8000)
	libQt5Core.so.5 => /usr/lib/libQt5Core.so.5 (0x00007f33a4de1000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007f33a4a59000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007f33a4755000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f33a453e000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007f33a41a0000)
	libpulse.so.0 => /usr/lib/libpulse.so.0 (0x00007f33a3f4f000)
	libQtCore.so.4 => /usr/lib/libQtCore.so.4 (0x00007f33a3a47000)
	libz.so.1 => /usr/lib/libz.so.1 (0x00007f33a3831000)
	libpython3.5m.so.1.0 => /usr/lib/libpython3.5m.so.1.0 (0x00007f33a3363000)
	libQt5Svg.so.5 => /usr/lib/libQt5Svg.so.5 (0x00007f33a310f000)
	libQt5OpenGL.so.5 => /usr/lib/libQt5OpenGL.so.5 (0x00007f33a2eb7000)
	libQt5PrintSupport.so.5 => /usr/lib/libQt5PrintSupport.so.5 (0x00007f33a2c47000)
	libQt5MultimediaWidgets.so.5 => /usr/lib/libQt5MultimediaWidgets.so.5 (0x00007f33a2a29000)
	libQt5QuickWidgets.so.5 => /usr/lib/libQt5QuickWidgets.so.5 (0x00007f33a2818000)
	libQt5WebKitWidgets.so.5 => /usr/lib/libQt5WebKitWidgets.so.5 (0x00007f33a25d3000)
	libQt5Quick.so.5 => /usr/lib/libQt5Quick.so.5 (0x00007f33a1fea000)
	libQt5WebKit.so.5 => /usr/lib/libQt5WebKit.so.5 (0x00007f339f944000)
	libQt5Sql.so.5 => /usr/lib/libQt5Sql.so.5 (0x00007f339f6fc000)
	libQt5XmlPatterns.so.5 => /usr/lib/libQt5XmlPatterns.so.5 (0x00007f339f10b000)
	libQt5Qml.so.5 => /usr/lib/libQt5Qml.so.5 (0x00007f339eb14000)
	libxcb.so.1 => /usr/lib/libxcb.so.1 (0x00007f339e8eb000)
	libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f339e6e7000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f339e4ca000)
	libproxy.so.1 => /usr/lib/libproxy.so.1 (0x00007f339e2a5000)
	libssl.so.1.0.0 => /usr/lib/libssl.so.1.0.0 (0x00007f339e034000)
	libcrypto.so.1.0.0 => /usr/lib/libcrypto.so.1.0.0 (0x00007f339dbbc000)
	libpng16.so.16 => /usr/lib/libpng16.so.16 (0x00007f339d986000)
	libharfbuzz.so.0 => /usr/lib/libharfbuzz.so.0 (0x00007f339d723000)
	libGL.so.1 => /usr/lib/libGL.so.1 (0x00007f339d4b1000)
	libicui18n.so.58 => /usr/lib/libicui18n.so.58 (0x00007f339d037000)
	libicuuc.so.58 => /usr/lib/libicuuc.so.58 (0x00007f339cc8b000)
	libpcre16.so.0 => /usr/lib/libpcre16.so.0 (0x00007f339ca22000)
	libglib-2.0.so.0 => /usr/lib/libglib-2.0.so.0 (0x00007f339c70f000)
	librt.so.1 => /usr/lib/librt.so.1 (0x00007f339c507000)
	libsystemd.so.0 => /usr/lib/libsystemd.so.0 (0x00007f33a8fab000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f33a8e58000)
	libpulsecommon-9.0.so => /usr/lib/pulseaudio/libpulsecommon-9.0.so (0x00007f339c284000)
	libjson-c.so.2 => /usr/lib/libjson-c.so.2 (0x00007f339c079000)
	libdbus-1.so.3 => /usr/lib/libdbus-1.so.3 (0x00007f339be29000)
	libutil.so.1 => /usr/lib/libutil.so.1 (0x00007f339bc26000)
	libQt5Sensors.so.5 => /usr/lib/libQt5Sensors.so.5 (0x00007f339b9e9000)
	libXrender.so.1 => /usr/lib/libXrender.so.1 (0x00007f339b7de000)
	libXcomposite.so.1 => /usr/lib/libXcomposite.so.1 (0x00007f339b5db000)
	libjpeg.so.8 => /usr/lib/libjpeg.so.8 (0x00007f339b371000)
	libwebp.so.6 => /usr/lib/libwebp.so.6 (0x00007f339b110000)
	libxslt.so.1 => /usr/lib/libxslt.so.1 (0x00007f339aecf000)
	libxml2.so.2 => /usr/lib/libxml2.so.2 (0x00007f339ab67000)
	libgobject-2.0.so.0 => /usr/lib/libgobject-2.0.so.0 (0x00007f339a915000)
	libgstreamer-1.0.so.0 => /usr/lib/libgstreamer-1.0.so.0 (0x00007f339a5e3000)
	libgstapp-1.0.so.0 => /usr/lib/libgstapp-1.0.so.0 (0x00007f339a3d5000)
	libgstbase-1.0.so.0 => /usr/lib/libgstbase-1.0.so.0 (0x00007f339a171000)
	libgstpbutils-1.0.so.0 => /usr/lib/libgstpbutils-1.0.so.0 (0x00007f3399f3c000)
	libgstvideo-1.0.so.0 => /usr/lib/libgstvideo-1.0.so.0 (0x00007f3399cb1000)
	libgstaudio-1.0.so.0 => /usr/lib/libgstaudio-1.0.so.0 (0x00007f3399a46000)
	libsqlite3.so.0 => /usr/lib/libsqlite3.so.0 (0x00007f3399735000)
	libQt5Positioning.so.5 => /usr/lib/libQt5Positioning.so.5 (0x00007f33994f5000)
	libQt5WebChannel.so.5 => /usr/lib/libQt5WebChannel.so.5 (0x00007f33992d8000)
	libXau.so.6 => /usr/lib/libXau.so.6 (0x00007f33990d4000)
	libXdmcp.so.6 => /usr/lib/libXdmcp.so.6 (0x00007f3398ece000)
	libfreetype.so.6 => /usr/lib/libfreetype.so.6 (0x00007f3398c11000)
	libgraphite2.so.3 => /usr/lib/libgraphite2.so.3 (0x00007f33989e5000)
	libexpat.so.1 => /usr/lib/libexpat.so.1 (0x00007f33987bb000)
	libxcb-dri3.so.0 => /usr/lib/libxcb-dri3.so.0 (0x00007f33985b8000)
	libxcb-present.so.0 => /usr/lib/libxcb-present.so.0 (0x00007f33983b5000)
	libxcb-sync.so.1 => /usr/lib/libxcb-sync.so.1 (0x00007f33981ae000)
	libxshmfence.so.1 => /usr/lib/libxshmfence.so.1 (0x00007f3397fab000)
	libglapi.so.0 => /usr/lib/libglapi.so.0 (0x00007f3397d7c000)
	libXext.so.6 => /usr/lib/libXext.so.6 (0x00007f3397b6a000)
	libXdamage.so.1 => /usr/lib/libXdamage.so.1 (0x00007f3397967000)
	libXfixes.so.3 => /usr/lib/libXfixes.so.3 (0x00007f3397761000)
	libX11-xcb.so.1 => /usr/lib/libX11-xcb.so.1 (0x00007f339755f000)
	libxcb-glx.so.0 => /usr/lib/libxcb-glx.so.0 (0x00007f3397343000)
	libxcb-dri2.so.0 => /usr/lib/libxcb-dri2.so.0 (0x00007f339713e000)
	libXxf86vm.so.1 => /usr/lib/libXxf86vm.so.1 (0x00007f3396f38000)
	libdrm.so.2 => /usr/lib/libdrm.so.2 (0x00007f3396d28000)
	libicudata.so.58 => /usr/lib/libicudata.so.58 (0x00007f3395228000)
	libpcre.so.1 => /usr/lib/libpcre.so.1 (0x00007f3394fb5000)
	libresolv.so.2 => /usr/lib/libresolv.so.2 (0x00007f3394d9e000)
	libcap.so.2 => /usr/lib/libcap.so.2 (0x00007f3394b9a000)
	liblzma.so.5 => /usr/lib/liblzma.so.5 (0x00007f3394974000)
	liblz4.so.1 => /usr/lib/liblz4.so.1 (0x00007f3394762000)
	libgcrypt.so.20 => /usr/lib/libgcrypt.so.20 (0x00007f3394453000)
	libgpg-error.so.0 => /usr/lib/libgpg-error.so.0 (0x00007f339423f000)
	libsndfile.so.1 => /usr/lib/libsndfile.so.1 (0x00007f3393fc7000)
	libasyncns.so.0 => /usr/lib/libasyncns.so.0 (0x00007f3393dc1000)
	libffi.so.6 => /usr/lib/libffi.so.6 (0x00007f3393bb8000)
	libgmodule-2.0.so.0 => /usr/lib/libgmodule-2.0.so.0 (0x00007f33939b4000)
	libgsttag-1.0.so.0 => /usr/lib/libgsttag-1.0.so.0 (0x00007f339377a000)
	liborc-0.4.so.0 => /usr/lib/liborc-0.4.so.0 (0x00007f33934fc000)
	libbz2.so.1.0 => /usr/lib/libbz2.so.1.0 (0x00007f33932ec000)
	libFLAC.so.8 => /usr/lib/libFLAC.so.8 (0x00007f3393076000)
	libogg.so.0 => /usr/lib/libogg.so.0 (0x00007f3392e6f000)
	libvorbis.so.0 => /usr/lib/libvorbis.so.0 (0x00007f3392c42000)
	libvorbisenc.so.2 => /usr/lib/libvorbisenc.so.2 (0x00007f339298f000)

**Comment by olav-st** [comment]
Yup, this shouldn't be there:
```
...
libQtCore.so.4 => /usr/lib/libQtCore.so.4 (0x00007f33a3a47000)
...
```
Try installing the Qt 5 version of QuaZip.

**Comment by lag-linaro** [comment]
You're a star!  Thank you so much.
