### ISSUE TITLE
Cannot upload a screenshot. missing oauth_cinsumer_key

### ISSUE THREAD

**Issue by Mmmikk** [olav-st/screencloud#255]
When I take a screenshot I cannot upload it. I get such error window from Screencloud:

"Can't verify request, missing oauth_consumer_key or oauth_token."

How can I make it work?

**Comment by olav-st** [comment]
How did you install ScreenCloud? Sounds like you're using a self-compiled version and forgot to add a consumer key.

**Comment by kafomambia** [comment]
"Upload failed!
Can't verify request, missing oauth_consumer_key or oauth_token
"
i also got the same error. How can i fix it

**Comment by PalePyth** [comment]
@olav-st 

I've downloaded the program via link "Windows XP/7/8" and got this:

![1241324123](https://user-images.githubusercontent.com/15071307/27747930-d52a30b6-5de6-11e7-9ec3-44ffdc0ffb6f.png)

After that I've downloaded the mirror for Windows and it still won't work. And how am I supposed to use it?

**Comment by DenisBabarykin** [comment]
@olav-st brilliant answer :)
