### ISSUE TITLE
All screenshots are black on GNOME 3.22

### ISSUE THREAD

**Issue by NighTurs** [olav-st/screencloud#257]
All screenshots I make are black screens, totally unusable. Seems like it is related to GNOME using wayland by default since 3.22. 

In logs I see following "org.gnome.Shell.desktop[763]: Window manager warning: Invalid WM_TRANSIENT_FOR window 0xa00007 specified for 0xa0001c (ScreenClou)."

Manjaro linux
Gnome 3.22
screencloud 1.3.1

**Comment by olav-st** [comment]
Are you using Wayland?

**Comment by NighTurs** [comment]
I do. I guess regular X apps go through XWayland, can be because of XWayland bug.. not sure.

https://aur.archlinux.org/packages/screencloud, @tate here describes the same problem.

**Comment by lamehost** [comment]
Any updates?
[This blog post](https://medium.com/@jock_tanner/its-not-ok-with-wayland-a89994fb68b5) says you can get rid of the issue by _disabling Wayland GTK+ backend throug the GDM config_, but i can't find how.

Also, that would be a temporary fix, is there any plan to add Wayland support?

**Comment by NighTurs** [comment]
@lamehost I believe guy from blog post just switched back to Xorg, you can follow instructions in [arch wiki](https://wiki.archlinux.org/index.php/GDM#Use_Xorg_backend).

**Comment by lamehost** [comment]
@NighTurs thanks.
For the records: it works.

Anyway i am more interested in getting Screencloud working on Wayland.
Are there any plans?

Thank you

**Comment by jasonkuehl** [comment]
I also have this issues

env | grep -i wayland
DESKTOP_SESSION=gnome-wayland
WAYLAND_DISPLAY=wayland-0
XDG_SESSION_TYPE=wayland
XDG_SESSION_DESKTOP=gnome-wayland
GDMSESSION=gnome-wayland

**Comment by camlafit** [comment]
Hello

Problem look always occur. Any new about this bug ?

Thanks a lot :)

**Comment by camlafit** [comment]
looks always accurate
