### ISSUE TITLE
Provide ScreenCloud AppImage for Linux

### ISSUE THREAD

**Issue by probonopd** [olav-st/screencloud#260]
Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Users would not have to rely on third-party packages or repositories, but could get the most recent version for Linux from the official download page (like for Windows and macOS)
- Works for most Linux distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Just one format for all major distributions
- Works out of the box, no installation of runtimes needed
- Optional(!) desktop integration with `appimaged`
- Binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can GPG2-sign your AppImages (inside the file)

[Here is an overview](https://github.com/probonopd/AppImageKit/wiki/AppImages) of projects that are already distributing upstream-provided, official AppImages.

Here is a __sample ScreenCloud AppImage for testing__:
https://bintray.com/probono/AppImages/ScreenCloud/_latestVersion#files

Here is the file used to control the deb to AppImage conversion:
https://github.com/probonopd/AppImages/blob/master/recipes/meta/ScreenCloud.yml

This is expected to run on most 2014-ish and later distributions, although some fine-tuning may be necessary. It has been generated from the existing trusty ppa. But seeing that this project is already using Travis CI to do continuous builds, we could bundle those up as AppImages as well.

Do you think this would be useful?
I'd be happy to help producing an official ScreenCloud AppImage.

**Comment by olav-st** [comment]
Hi,

I'd love to standardize the Linux version in one format! Pushing a new version is quite a pain at the moment because of all the different combinations of distro + package format.

I've already started experimenting with [Snappy](https://www.ubuntu.com/desktop/snappy) (as you can see here: https://github.com/olav-st/screencloud/blob/master/deploy/linux/snapcraft.yaml), but I've been held back by [this bug](https://bugs.launchpad.net/snappy/+bug/1600136) that prevents the tray icon from working. I haven't followed the evolution of the "universal" package formats, but if AppImages are on their way to become the standard then I'm all for producing an official AppImage. 

Thanks a lot for offering to help :)

**Comment by probonopd** [comment]
@olav-st 
Did you have a chance to test the sample ScreenCloud AppImage?

> if AppImages are on their way to become the standard then I'm all for producing an official AppImage

For the forseeable future, I expect there there will likely be a peaceful co-existence of AppImage, snap, and Flatpak - each of those have slightly different objectives. As for AppImage, the focus is on a no-frills, no-runtimes, no-installation "one app = one file" approach that works on all major distributions, and we are seeing [a lot](https://github.com/probonopd/AppImageKit/wiki/AppImages) of adoption lately.

**Comment by rikai** [comment]
@olav-st Looks like that Snappy bug just got fixed upstream, so hopefully that blocker is gone! 👍

**Comment by olav-st** [comment]
I've tinkered a little with AppImages and started working on a .yml file for ScreenCloud (https://github.com/olav-st/screencloud/blob/master/deploy/linux/appimage.yml). It dosen't fully work yet, but it's a start!

As for Snappy, I've encountered another bug https://github.com/ubuntu/snapcraft-desktop-helpers/issues/62. 👎

**Comment by probonopd** [comment]
Cool that you are building it on OBS. Let me know if you run into rough edges, since the OBS AppImage support is still relatively new.

**Comment by olav-st** [comment]
I'm currently stuck on the following error from linuxdeployqt:
```
ERROR: ldd outputLine: "libpulsecommon-7.0.so => not found"
ERROR: Please ensure that all libraries can be found by ldd. Aborting.
```
I tried adding `libpulse0` to the list of packages but I still get the same error. I tried installing the same package on an OpenSuse VM and the package gave me `libpulsecommon-9.0.so` instead of `ibpulsecommon-7.0.so`. I'm not that familiar with RPM-distros so please tell me if I'm doing something obviously wrong.

**Comment by probonopd** [comment]
insert `cp /usr/lib*/pulseaudio/* /usr/lib*/` before the `linuxdeployqt` calls. https://github.com/probonopd/linuxdeployqt/issues/52

**Comment by olav-st** [comment]
Thanks, I had to change it to 
```bash
cp /usr/lib*/pulseaudio/* /usr/lib64/ || cp /usr/lib*/pulseaudio/* /usr/lib/
```
to make it work on 64-bit, but the AppImage builds successfully now 👍 I haven't tested it yet, but it's available here: https://build.opensuse.org/package/binaries/home:olav-st:branches:OBS:AppImage:Templates/ScreenCloud?repository=AppImage

**Comment by probonopd** [comment]
Almost working. Please install to `usr/bin` rather than `usr/local/bin`...

**Comment by probonopd** [comment]
And remove the symbolic link to `screencloud-1.3.1'

**Comment by probonopd** [comment]
Apart from that... working on openSUSE LEAP 42.2 :-)

![screenshot_20170610_131405](https://user-images.githubusercontent.com/2480569/27002301-c9b506ce-4dde-11e7-9606-0a0997825cfc.png)

**Comment by olav-st** [comment]
The `/usr/local` thing is a CMake quirk. I've set the CMAKE_INSTALL_PREFIX to only /usr (https://github.com/olav-st/screencloud/commit/9ceb5be9ecf89b41c3ccfbee620d6209244ce41e) and the AppImage seems to work without further modifications now. 😄 

(ARM builds don't seem to work, but whatever...)

**Comment by probonopd** [comment]
Would be nice to see working ARM builds too. Can you make sense of the errors in the build log?

**Comment by olav-st** [comment]
Seems to be related to OpenGL. Could be that some libraries are missing or are using different versions compared to x86.

**Comment by probonopd** [comment]
Not sure... I was able to build for ARM on obs, http://download.opensuse.org/repositories/home:/probono/AppImage.arm/

This is an example `appimage.yml`:
https://build.opensuse.org/package/view_file/home:probono/DSRemote/appimage.yml?expand=1

**Comment by probonopd** [comment]
`  - cp $BUILD_APPDIR/usr/share/applications/screencloud.desktop $BUILD_APPDIR´ should not be needed, as `linuxdeployqt` should take care of that for you.

**Comment by olav-st** [comment]
Ok, thanks. Removed (https://github.com/olav-st/screencloud/commit/8eafa0188be4736e7a292a6a849d2d4fc63bd164)

**Comment by olav-st** [comment]
Quick question. I tried adding AppStream metadata for ScreenCloud and I get this while building:
```
[  406s] AppStream upstream metadata found in usr/share/metainfo/screencloud.appdata.xml
[  406s] [32;1mI - <unknown>:<root>[0m
[  406s]     No AppStream metadata was found.
[  406s] 
[  406s] Validation was successful.
```
Does this mean that there was an error or was the metadata parsed successfully?

**Comment by probonopd** [comment]
I think "successful" really means "successful" here ;-)

**Comment by probonopd** [comment]
Download seems to be gone again?

Reference:
https://github.com/AppImage/AppImageHub/issues/15

**Comment by AlonsoEnrique** [comment]
@olav-st the snap issue as been resolved, see the last comment: https://github.com/ubuntu/snapcraft-desktop-helpers/issues/62

**Comment by probonopd** [comment]
Looks like https://github.com/olav-st/screencloud/releases doesn't have the AppImage...

**Comment by AlonsoEnrique** [comment]
@probonopd the present and the future is snap and flatpak, this https://www.omgubuntu.co.uk/2018/05/nautilus-remove-ability-launch-binaries-apps affect to AppImage

**Comment by probonopd** [comment]
GNOME is reverting this change. https://gitlab.gnome.org/GNOME/nautilus/merge_requests/229

The present and the future is snap, flatpak, and _AppImage_ 👍

**Comment by AlonsoEnrique** [comment]
@probonopd oooh :1st_place_medal:. Question: any problem with snap or flatpak?

**Comment by probonopd** [comment]
They are different solutions for different needs. AppImage is about "portable apps" that need no installation and can be copied e.g., on a USB stick that runs a Live ISO.

**Comment by probonopd** [comment]
```
+'[' -f database/ScreenCloud/screencloud.appdata.xml ']'
+./appstreamcli-x86_64.AppImage convert database/ScreenCloud/screencloud.appdata.xml database/ScreenCloud/appdata.yaml
Could not parse XML data.
```

The AppStream file seems to be broken. You could use http://output.jsbin.com/qoqukof to generate a working one with minimal hassle.

Reference:
https://github.com/AppImage/appimage.github.io/pull/753

**Comment by olav-st** [comment]
There's now an AppImage available from the website and also here: https://github.com/olav-st/screencloud/releases/tag/v1.4.0 :)

**Comment by probonopd** [comment]
Thank you very much. Looking awesome!
