### ISSUE TITLE
Failed to upload to server and not connecting to dropbox

### ISSUE THREAD

**Issue by suddenhit** [olav-st/screencloud#263]
When trying to upload image for several days now getting the following error
<img width="252" alt="screenshot at 08-37-54" src="https://cloud.githubusercontent.com/assets/5830459/22551526/110a45b4-e923-11e6-97f8-5eb0a84a276d.png">
 
Also when trying to enter the access code from Dropbox it just doesn't accept it.

**Comment by olav-st** [comment]
For the first issue, see https://github.com/olav-st/screencloud/issues/266

I'm unable to reproduce the second issue, can you try running ScreenCloud from the command prompt like this:
`ScreenCloud.exe 1> output.txt 2>&1`
and paste the output.txt file here?
