### ISSUE TITLE
https://screencloud.net/ down

### ISSUE THREAD

**Issue by aistis-** [olav-st/screencloud#266]
Hi!

I see at the moment that https://screencloud.net/ is down, screens upload also does not work. The last two weeks it is not the first time :(

It returns 504 by nginx

**Comment by OnkelTem** [comment]
Confirming

**Comment by studioart** [comment]
same here: "502 Bad Gateway"
@olav-st could you please fix it? Thx.

**Comment by Nek-** [comment]
is it definitive ?

**Comment by olav-st** [comment]
I applied the same fix as last time, but it seems like it's temporary. Looks like a problem with the backend storage server, I'll try to find a better solution.

**Comment by olav-st** [comment]
There was a problem generating IDs for new screnshots, I've pushed a fix so it should be working again now. I'll give it some time before I close the issue just to be sure, would be nice if people could confirm that it's working for them :)

**Comment by OnkelTem** [comment]
@olav-st  
> I've pushed a fix
Does it mean we should updated the client?

**Comment by olav-st** [comment]
@OnkelTem Nope, the fix is on the server side only

**Comment by OnkelTem** [comment]
Oh, thanks. Sorry :)

**Comment by studioart** [comment]
at my side all is working fine currently, thanks.

**Comment by edison23** [comment]
I know this is old issue, but for me for past few days it's relevant, as my uploads started failing and https://screencloud.net/ is giving me error 502 Bad Gateway .. I wonder if I started doing something wrong

**Comment by aistis-** [comment]
Also not working anymore :disappointed:

**Comment by OnkelTem** [comment]
I confirm
