### ISSUE TITLE
[Suggestion] Randomized short name

### ISSUE THREAD

**Issue by mobbdeep** [olav-st/screencloud#272]
Hello,

I am wondering if there can be an ability of having randomized short names similar to other upload sites. For example; in FPT settings, you can create a name to identify your screenshots each time you take one. The best I figured was using PHP date/time combinations and throwing in random letters and numbers but instead, I'd like something shorter. 

Eg. domain.com/sbUyR3.png or something and the combination will be randomized each time you take a screenshot.

Thank you.

**Comment by olav-st** [comment]
See https://github.com/olav-st/screencloud/issues/10.
