### ISSUE TITLE
RE: #10

### ISSUE THREAD

**Issue by mobbdeep** [olav-st/screencloud#273]
This is regarding #10 - Is there a reason why when using {rnd_s}, it includes apostrophes in the string? Eg. My current output example right now is b'KTqpLE5N'.png but I was wondering if those apostrophes can be removed? They're also generated in that same sequence every time.

Thank you!

**Comment by olav-st** [comment]
This is a Python 2 / Python 3 compatibility issue, but please keep the discussion in https://github.com/olav-st/screencloud/issues/10. Opening new issues just causes more clutter.
