### ISSUE TITLE
Upload failed! Failed to write /imgs//Screenshot.png. Check permissions. - SFTP

### ISSUE THREAD

**Issue by Workinq** [olav-st/screencloud#274]
I don't know why this is happening but whenever I attempt to write the file to my SFTP server it mentions this error message: 

> Upload failed!
Failed to write /imgs//Screenshot.png. Check permissions.

I have already set the permissions to 777 but it still doesn't work... 
![screen shot 2017-04-11 at 16 12 07](https://cloud.githubusercontent.com/assets/16672491/24916351/cd21f6dc-1ed1-11e7-8005-68a086dd5c28.png)

Please could somebody help me with this issue, thank you.

**Comment by pfoo** [comment]
Are you by any chance chrooting your users using openssh built-in ChrootDirectory option ?
If this is the case, is the directory you are chrooting to owned by root ? This is mandatory.
