### ISSUE TITLE
App seems to crash when trying to cap on my new Macbook Pro

### ISSUE THREAD

**Issue by olshiftyeye** [olav-st/screencloud#275]
### Current Behavior

I purchased a new MBP yesterday (the one with the nifty touchbar), but the app seems to crash when I try to screen cap. I can open the app, it appears in my menu bar, and I can update preferences and whatnot. But then when I used the hotkeys to capture my screen, nothing happens. When I check the menu bar, the app is no longer there.

### Expected Behavior

When I try to use the hotkeys to cap my screen, the app should not crash and I should be able to capture my screen as I've done so many times before.

### Steps to reproduce

- [ ] OPTIONAL: Purchase a new 15" Macbook Pro from your local Apple store (or online). You could also just borrow someone else's.
- [ ] Install ScreenCloud 1.3.0 for Mac.
- [ ] Open the app.
- [ ] Attempt to screen grab using the hotkeys set in preferences.
- [ ] App crashes.

### Notes

I have used this app for years and it's a core part of my everyday workflow. Please fix if possible. I really don't want to have to search and find another tool. Yours has been perfect so far.

**Comment by chamunks** [comment]
I get basically the same thing as of the latest version of OS X I'd post a screenshot but...

```
macOS Sierra
Version 10.12.5
```
iMac late 2013

**Comment by Leopere** [comment]
He’s dead Jim
