### ISSUE TITLE
All captures are black screens

### ISSUE THREAD

**Issue by rootbear75** [olav-st/screencloud#276]
I can't get screencloud to stop overlaying itself in front of everything.  It only captures black screens now.

Left screen is normal desktop.
Middle screen is a remote desktop session where it's working fine.
Right screen is how it's currently capturing images.

![screencloud issue](https://cloud.githubusercontent.com/assets/2320924/25302078/2057904e-26ea-11e7-8118-b0323be1a52c.png)

Here is a below sample of what it's capturing when selecting a region. Same happens on Window and Full Desktop as well

![image](https://cloud.githubusercontent.com/assets/2320924/25302081/36b8702e-26ea-11e7-8150-721a8ee354d5.png)

Any help would be appreciated or I'll have to find another software to use. I love screencloud :)

**Comment by rootbear75** [comment]
I've already tried uninstalling and reinstalling the software.

**Comment by Naatan** [comment]
Same issue on Arch linux. Worked fine on Ubuntu.

**Comment by Naatan** [comment]
I think this is an issue with some underlying dependency as I've tried various screenshots app and they all had similar problems (except for a few). Gnome screenshots seem to work fine but they have their own set of problems.

Anyone know what dependency might be at fault here? Screencloud is the only app I've come across that does exactly what I want in terms of features, nothing more and nothing less.

**Comment by rootbear75** [comment]
I've ended up swapping over to ShareX honestly. No response on this thread in 5 months makes me think dev is fine with the bug (shrug)  I need something that works in the meantime

**Comment by Naatan** [comment]
I'll have to check that out, thanks for sharing. I've been using flameshot but it doesnt allow window capture :\

**Comment by a2media** [comment]
Same issue on Ubuntu 19.04

**Comment by antongorodezkiy** [comment]
The same issue on Ubuntu, probably related to Wayland

**Comment by rootbear75** [comment]
In case anyone cares, I found out why it wasn't working on my system.  My A/V had identity protection and was causing screencloud to not be able to take a picture of the desktop
I used Webroot
