### ISSUE TITLE
PythonQt 3.2 issues

### ISSUE THREAD

**Issue by AlfredoRamos** [olav-st/screencloud#281]
The new PythonQt version changed the libraries naming convention, so now they're generated depending on the Qt and Python versions that were used to build the library.

https://sourceforge.net/p/pythonqt/news/2017/06/pythonqt-32-released/

```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
PYTHONQT_LIBRARY (ADVANCED)
    linked by target "screencloud" in directory /home/alfredo/Desktop/screencloud-git/src/screencloud

-- Configuring incomplete, errors occurred!
See also "/home/alfredo/Desktop/screencloud-git/src/build/CMakeFiles/CMakeOutput.log".
```

I added `PythonQt-Qt5-Python3` and `PythonQt_QtAll-Qt5-Python3` in the cmake modules `FindPythonQt.cmake` and `FindPythonQt_QtAll.cmake` respectively to detect both libraries.

I've made a patch for the `screencloud-git` AUR package with these changes, but maybe there's a better/proper way to fix it.

[fix_pythonqt.patch](https://aur.archlinux.org/cgit/aur.git/tree/fix_pythonqt.patch?h=screencloud-git)

**Comment by AlfredoRamos** [comment]
Another possible way to fix it:

[ fix_pythonqt_detection.patch ](https://gist.github.com/AlfredoRamos/b83046b8686840db656c08f175bd8f10)

**Comment by olav-st** [comment]
Your second solution looks good, but I'm assuming it won't work for Qt4 builds? (Since [5-9] is used to match the version number)

**Comment by olav-st** [comment]
I've applied a modified version of your patch (changed 5 to 4). I'll try a Qt4 build with it ASAP. https://github.com/olav-st/screencloud/commit/386bc72e6743e7cbbbf0a22f587458e6b18edb6c

**Comment by AlfredoRamos** [comment]
I didn't send a pull request because I don't know if it would work on every OS, especially for Windows.

```
string(REGEX REPLACE "^lib(.+)\\.so$" "\\1" PYTHONQT_LIB "${PYTHONQT_LIB_FILE}")
```

I was trying to get it working using `CMAKE_FIND_LIBRARY_PREFIXES` and `CMAKE_FIND_LIBRARY_SUFFIXES` but I don't know cmake enough to do it, that way it might work for Windows, Mac and other Linux systems where the library prefix is not `lib` (if any).
