### ISSUE TITLE
Multi Monitor Setup Capture Problems

### ISSUE THREAD

**Issue by embluk** [olav-st/screencloud#284]
I'm running KDE neon and the screen cloud app seems to work well expect when I take a screen shot with the area capture, because I have 3 monitors inside the area capture mode it tries to bring my monitors all onto the screen that I am trying to take a screenshot on. Here is an example of what it kinda looks like: http://i.imgur.com/VvWGcPV.jpg

It also does something similar on the full screen capture as it brings my second monitor onto my middle monitor... And if I try to take an area capture on my other monitors it sometimes displays my far left monitor on my right monitor as well.

The built in screenshot app on neon has no issues taking full screen, area or window shots.

**Comment by pajadam** [comment]
It works as described on my 3 monitor setup using Gnome 3 with **X.org**, and when I'm running **Wayland**, the screen is black using all 3 types of screenshot.

**Comment by Mayurifag** [comment]
I have 3 monitors with different resolutions (2: 1920×1080, 1: 1280×1024). 
Also having problems with cinnamon latest version. Everything was okay when I had only one monitor.

**Comment by embluk** [comment]
Since switching to Ubuntu Gnome 17.04 everything seems ok on my laptop, on my desktop I switched to using Linux Mint and it all seems to be working correctly...
