### ISSUE TITLE
suggestion: Capture from image-file -or- edit image file

### ISSUE THREAD

**Issue by Kaleidosko** [olav-st/screencloud#285]
Hello everyone,

currently I use hotshots for my German "it description knowledge base". 
But Hotshots is no longer under development and does not run native under linux. So I found screencloud and it is awesome. But one thing I miss: re-edit image files....

When I create a screenshot, write some annotation and save the image I have no chance to add more annotation because there is no "open image" option. It would be awesome if we could open the images again to add more annotation to them.

Greetings

**Comment by magicvince** [comment]
+1
