### ISSUE TITLE
Linux: Image goes all broken

### ISSUE THREAD

**Issue by bhcopeland** [olav-st/screencloud#287]
Running Arch Linux with AMDGPU. It was working fine, but when I create a image now, the screen overlay breaks.

http://i.imgur.com/V50ZGmm.png

**Comment by xl4m3rx** [comment]
Same problem here with Manjaro and NVIDIA GPU

**Comment by meganukebmp** [comment]
Can confirm. AMDGPU, only second monitor does this.

**Comment by z-engine** [comment]
Same problem with Arch Linux and Nvidia card. When I take a screenshot on primary display the image is glitched
