### ISSUE TITLE
При всём уважении, но как же вы за****ли

### ISSUE THREAD

**Issue by OnkelTem** [olav-st/screencloud#294]
У меня PREMIUM подписка, чуваки и уже давно. Настолько вот я люблю ваш сервис. Но через день я не могу пользоваться сервисом из-за ошибки:

```
Upload failed!
Illegal parameters. name and description must be a string, file must be a jpg, png or gif.
```

и насколько мне известно это продолжается уже хз сколько времени и затрагивает вообще всех пользователей. Ну сколько уже можно!? Почините уже.

Sorry for Russian, но по-моему вам по фиг на эти тикеты, да? Please don't ask me to translate, I won't. Use google dictionary. This is inconvenience, I know. Now THINK about OUR inconveniences when we CAN NOT use your service due to YOUR problems.

**Comment by rbt2008** [comment]
Так написано же что премиум всё, денег хватает еле на поддержание жизни сервера https://screencloud.net/pages/hosting-phaseout-announcement

Лучше все скачать и использовать другой сервак для синхронизации

**Comment by OnkelTem** [comment]
@rbt2008 Спасибо, не видел! Печаль :( Мне больше всех он нравился.

**Comment by olav-st** [comment]
Closing this due to language barrier
