### ISSUE TITLE
Unable to upload a screenshot

### ISSUE THREAD

**Issue by romeozi** [olav-st/screencloud#295]
I have a problem with uploading screenshots to screencloud.
After a screenshot I get the error:

```
Upload failed!
Failed to parse response from server

```
In the console I have:

```
Got a buffer underflow! 
[WARN] "Error while playing audio. Code: 3" 
[INFO] "Uploading screenshot to 'screencloud'. Size: 169248 bytes" 
[INFO] "<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.4.6 (Ubuntu)</center>
</body>
</html>
" 
[WARN] "Failed to parse response from server"
```

**Comment by rgrauphics** [comment]
Unable to upload to screencloud server with a different error in Linux & Mac.

Upload failed!
Illegal parameters. name and description must be a string, file must be a jpg, png or gif

**Comment by olav-st** [comment]
Closing this since the screenshot hosting service has been shut down
