### ISSUE TITLE
Dropbox's v1 API is deprecated

### ISSUE THREAD

**Issue by damianharouff** [olav-st/screencloud#297]
Dropbox's v1 API was deprecated last year, and that endpoint was shut off today: https://blogs.dropbox.com/developers/2016/06/api-v1-deprecated/

Dropbox upload via Screencloud no longer works.

It seems like Screencloud is pretty much dead. Numerous open issues with no response, no real updates in a couple of years. Anyone know of a good replacement for uploading screenshots to Dropbox?

**Comment by olav-st** [comment]
Fixed by https://github.com/olav-st/screencloud-plugins/pull/35
