### ISSUE TITLE
Can't connect to Dropbox

### ISSUE THREAD

**Issue by rgrauphics** [olav-st/screencloud#300]
Trying to connect to dropbox on Mac & Linux (mint) both OS' just sit there and never launch a browser to connect.

I have removed and redownloaded with the same issues. I have also moved (backedup) the config file and started over. 

Any fix?

**Comment by srolskyi** [comment]
I have some problem! After installing plugin dropbox I can't connect to my Dropbox account, because "login form" never opening.
