### ISSUE TITLE
Cant change settings with Gnome + Dash to Panel

### ISSUE THREAD

**Issue by kenji-1996** [olav-st/screencloud#303]
The icon for ScreenCloud is not coming up. I see Discord, Chrome but not ScreenCloud to modify my settings.

I am running Gnome on Ubuntu 16.04 with Dash to Panel extention as seen here:
[https://i.imgur.com/aUuoVHi.png](url)

Is there a CMD line for opening/modifying the settings? the 'help/support' docs seemingly provide no information on this

**Comment by olav-st** [comment]
I guess the best way would be to manually edit the configuration file. It's located in `~/.config/screencloud/ScreenCloud.conf`
