### ISSUE TITLE
Login issus

### ISSUE THREAD

**Issue by rfcdejong** [olav-st/screencloud#305]
I want to download all my screenshots, but I cannot login anymore? Is anyone else able to login?

**Comment by TeplyyMaksim** [comment]
Everytime I want to login or save screenshot to cloud server responses with MySQL error. Pls, fix my favorite screenshotservice. I love it and I need it right now!)

**Comment by titulus** [comment]
can't login too

**Comment by navjotjsingh** [comment]
https://screencloud.net/pages/hosting-phaseout-announcement

**Comment by olav-st** [comment]
Closing this since the screenshot hosting service has been shut down
