### ISSUE TITLE
ScreenCloud download isn't working

### ISSUE THREAD

**Issue by Lillecarl** [olav-st/screencloud#306]
Hi!

The ScreenCloud download links doesn't work on the website. If you want to take that load off your servers you can upload the files to github as releases :)

**Comment by olav-st** [comment]
Same problem as in https://github.com/olav-st/screencloud/issues/317. Now fixed. Thanks for letting me know :) 

Also, the files are mirrored on SourceForge (at https://sourceforge.net/projects/screencloud/files/) in case this problem arises again.
