### ISSUE TITLE
GPG key expired

### ISSUE THREAD

**Issue by Pelt10** [olav-st/screencloud#308]
Hello,

When I run an "apt-get update" command, apt returns an error related to your expired GPG key:

> Err:14 http://download.opensuse.org/repositories/home:/olav-st/Debian_9.0  Release.gpg
  Les signatures suivantes ne sont pas valables : EXPKEYSIG 1BE1E8D7A2B5E9D5 home:olav-st OBS Project <home:olav-st@build.opensuse.org>

**Comment by embluk** [comment]
Yes I get the same thing, this needs sorting otherwise it makes it annoying when updating using apt-get.

**Comment by vash1486** [comment]
I've the same problem!

**Comment by seroy** [comment]
Sadenly, it seems like project dies, see https://screencloud.net/pages/hosting-phaseout-announcement
Maybe someone make fork and will become a new maintainer?

**Comment by Pelt10** [comment]
It's look like a good idea, but who?

**Comment by vash1486** [comment]
well, as far as I understand, not the entire project, Thoresen speak about "phasing out the hosting service" because "effort spent maintaing it could be better spent on the desktop client"

**Comment by joubertredrat** [comment]
Same problem here.

```bash
root@dev:~
➤ apt-key list | grep "expired"
pub   rsa2048/A2B5E9D5 2013-08-11 [SC] [expired: 2017-12-27]
uid         [ expired] home:olav-st OBS Project <home:olav-st@build.opensuse.org>

```

**Comment by olav-st** [comment]
The repositories on OBS are no longer maintained (since they were a pain to maintain!). Use the snap or AppImage version instead.
