### ISSUE TITLE
Low Resolution Screenshots

### ISSUE THREAD

**Issue by Beags** [olav-st/screencloud#310]
Hello, 

I use a 2016/2017 15 inch Macbook Pro, and I am having issues of the screenshot being lower resolution than the display. 

https://buzzzy.co/i/3OdgEEA0.png

Take this one for example, it is a much lower resolution than the display. I am wondering if there will be a fix soon.

**Comment by BigJazzz** [comment]
I've also been noticing that sometimes my screenshots are of low quality. Not sure what the trigger is though, as I can also get normal quality screenshots.
