### ISSUE TITLE
Cant add sftp host

### ISSUE THREAD

**Issue by louisoft01** [olav-st/screencloud#314]
![image](https://user-images.githubusercontent.com/14853615/39379931-b82473b8-4a54-11e8-96e2-a90a52ec55e9.png)
I get this error when trying to add a sftp file host, Arch Linux using the git build from the AUR
I have tried install python2-paramiko and python-paramiko with neither sorting the problem

**Comment by olav-st** [comment]
Do you have the same problem if you use the Appimage from https://github.com/olav-st/screencloud/releases?

**Comment by mpawlak96** [comment]
I have the same problem :(

**Comment by olav-st** [comment]
Do you get any output if you run ScreenCloud from the terminal?

**Comment by mpawlak96** [comment]
if u open app by open -a Screencloud.app im getting the same errors

![zrzut ekranu 2018-08-29 o 08 03 24](https://user-images.githubusercontent.com/34542996/44768622-2fafdf80-ab62-11e8-8b41-6d497a6aa319.png)
![zrzut ekranu 2018-08-29 o 08 03 30](https://user-images.githubusercontent.com/34542996/44768623-2fafdf80-ab62-11e8-9757-391557ce3b87.png)
