### ISSUE TITLE
site https issues and bad download link

### ISSUE THREAD

**Issue by flosb** [olav-st/screencloud#317]
Hey guys, couldn't find the contact form on https://screencloud.net/ and I don't have twitter (btw the contact us button on http://heybigname.com/ is misleading - makes me think there should've been a contact form popup/link something, not just a page anchor - i'm referring to the one that is below your names, not the one in the menu)

Just wanted to let you know that the let's encrypt certificate on https://screencloud.net/ has expired, and the Windows Windows Vista/7/8/10 Download link does not work (redirects to homepage).

Thanks for this lovely software, makes my life easier everyday.

Cheers! :)

**Comment by olav-st** [comment]
Thanks for letting me know :) Fixed
