### ISSUE TITLE
ScreenCloud does not save preferences across process instances [Version 1.30, Ubuntu 16.04]

### ISSUE THREAD

**Issue by silicWulf** [olav-st/screencloud#327]
ScreenCloud does not preserve its preferences (hotkeys, ssh settings) across process starts. Simple as that.

Installed on Ubuntu 16.04 using [these instructions.](http://ubuntuhandbook.org/index.php/2017/06/install-screencloud-ubuntu/) (OpenSUSE repo install).

**Comment by olav-st** [comment]
Try using the AppImage from here instead: https://github.com/olav-st/screencloud/releases
The packages from the Open SUSE build service are no longer maintained.

**Comment by silicWulf** [comment]
Seems that using the AppImage causes errors within the `Crypto` module for sftp. Using Python 2's PyCrypto, a syntax error is raised. Using Python 3's PyCrypto, an ImportError is raised:
```
File "/home/user/.local/share/screencloud/ScreenCloud/plugin/sftp/modules/Crypto/Util/Counter.py", line 59, in <module>
    from Crypto.Util import _counter
ImportError: cannot import name '_counter'```
I'm unfamiliar with the internals of PyCrypto, but this error did not occur with the OpenSUSE repo's version of ScreenCloud. `Crypto/Util/_counter.py` exists in neither the py3 version of PyCrypto, nor the py2 version of PyCrypto.

**Comment by olav-st** [comment]
I'm unable to reproduce this issue on a clean install of Ubuntu 16.04. You shouldn't need to have PyCrypto or Paramiko installed, so maybe the system versions are interfering.
