### ISSUE TITLE
Apple Retina Display

### ISSUE THREAD

**Issue by BirknerAlex** [olav-st/screencloud#33]
Hello,

Screencloud got problems with capturing a screenshot on a MacbookPro with Retina display.

If I try to capture a Window the screenshot got the normal size (like there if there is no retina display) and not the correct resolution for the Retina display.

This was a try to make a screenshot from the OSX Terminal: http://bit.ly/1lO3EI5 

Normally it should be looking like this (screenshot was made native with OSX):
![bildschirmfoto 2014-01-12 um 00 32 25](https://f.cloud.github.com/assets/779751/1895169/e4d80704-7b18-11e3-8209-b021e90ca371.png)

**Comment by leisegang** [comment]
Any news on the selection tool and pixelation?
When i take a screenshot with screencloud it gets pixelated, when using JING it takes a screenshot in retina, making it a larger png than the selected area. A 5cm selection becomes almost 10cm. I think that is because of the PPI on retina.
