### ISSUE TITLE
Screencloud 1.4.0 opens a new desktop for capture selection on OSX

### ISSUE THREAD

**Issue by cuddylier** [olav-st/screencloud#330]
Hi

Screencloud 1.4.0 opens a new desktop that shows an image of the screen when I pressed my hotkey for capture selection on OSX 10.13.5, this did not occur on 1.3.1, I just remained on the main desktop without any new ones being created. The new one being created by screencloud 1.4.0 is called 'ScreenCloud' and just shows a black screen after I make the selection making everything very cumbersome. The screenshot comes out okay still, I can only assume the additional desktop being created vs version 1.3.1 is a bug.

Capture active window and capture full screen both work fine.

Thanks

**Comment by diveint** [comment]
I have this same exact issue. High Sierra 10.13.6

![screen shot 2018-09-13 at 3 41 12 pm](https://user-images.githubusercontent.com/31827954/45511627-81b05200-b76b-11e8-8455-193ac72d04e3.png)

**Comment by f22z2nfr22z2n** [comment]
Hi,
I also have exactly the same problem. After updating to High Sierra 10.13.6 and Screencloud 1.4.0 this very intrusive bug makes using screencloud kind of problematic.
Thank you!

**Comment by ekallevig** [comment]
Just installed screencloud and having the same issue

**Comment by fharper** [comment]
Still an issue.

**Comment by jakimfett** [comment]
Still an issue in v1.5.0 on macOS 10.13.6

**Comment by Veyfeyken** [comment]
Would really appreciate a fix. Still an issue on macOS 10.15.2.

**Comment by petehanson** [comment]
Same here, just installed 1.5.1 on Catalina and see the same behavior.
