### ISSUE TITLE
Screencloud error

### ISSUE THREAD

**Issue by Schlauer-Hax** [olav-st/screencloud#335]
When I run Screencloud it says "ScreenCloud requires a system tray to function properly. [...]". The problem is when I install sni-qt it doesn't change. indicator-application is already installed. The problem occurs when I install it with snap or use it as AppImage. I'm using Elementary OS 5.0. Thanks for help

**Comment by Schlauer-Hax** [comment]
@nmiroshnichenko elementary os 5 is  based in ubuntu 18.04.1

**Comment by olav-st** [comment]
I don't think the distribution is the problem here. The desktop environment is likely the culprit. ScreenCloud works on GNOME the way it ships with Ubuntu 18.04. Haven't tested on other desktop environments.

**Comment by Schlauer-Hax** [comment]
@olav-st ok so how can i run screencloud without this tray? is there any option to open the settings without the tray?

**Comment by olav-st** [comment]
@Schlauer-Hax Not at the moment, but that would definitely be a useful feature!

**Comment by auvio323** [comment]
At the moment, the only real way to fix this issue as what I have done, is to re-enable the legacy system tray on gnome. You would need to install "gnome-shell-extension-appindicator" on your distro, relogin. Then search "Extensions" on your gnome (it may be tweaks if you are on an older version of gnome, i am using gnome 40), and then enable "KStatusNotifierItem/AppindIcator Support". Then once you've done that, relogin and it should work fine. I have done this and it worked completely fine for me. If you don't want to reenable the system tray, then i believe screenshotting still works with the keybind, so you would do "ALT + Shift + 2" (selection) or "ALT + Shift + 1" (entire screen) to screenshot, as even though it gives that error, screenshotting still works with keybinds. Hope this helps!
     - auvio
