### ISSUE TITLE
Can't Configure Dropbox

### ISSUE THREAD

**Issue by mzubairharoon** [olav-st/screencloud#336]
Just download latest version from the site, but it gives error on dropbox service.

![image](https://user-images.githubusercontent.com/1677847/47489457-1e343c80-d860-11e8-80eb-76f2fcc59ff8.png)

Anyway to fix it?

Thank you

**Comment by danielricecodes** [comment]
Dropbox isn't working for me either.  When I enter the code that Dropbox generates, the app does nothing.  I'm sure its probably something with the dropbox API.  I'd fix it, but I'm a Ruby developer - I haven't programmed C++ in 20 years :laughing:
