### ISSUE TITLE
NotImplementedError

### ISSUE THREAD

**Issue by ColinShark** [olav-st/screencloud#339]
Hey there,

I'm trying to upload a screenshot to a SFTP Server with username+password, but on saving I get the Error below and I have absolutely no idea what to do to solve this.

![image](https://user-images.githubusercontent.com/33236409/48900065-9f77f280-ee51-11e8-9b27-26b390972907.png)

Any help is appreciated,
Thanks in advance

EDIT:
Sometimes I get this error when accessing the config for SFTP upload:
![image](https://user-images.githubusercontent.com/33236409/48900311-55434100-ee52-11e8-8b88-935e919d325a.png)

**Comment by olav-st** [comment]
Haven't checked, but it might be that the version of PyCrypto that ships with ScreenCloud is old and dosen't support the crypto-stuff used in newer SSH servers.

**Comment by ColinTheShark** [comment]
Welp, how would I update that on a windows 10?
Bare in mind that I'm not that tech savvy :/

**Comment by Loued** [comment]
I have the same problem. That keep me from updating my old 1.1.6 version that still work.

**Comment by ColinShark** [comment]
Bruh.
