### ISSUE TITLE
screencloud\python35.zip\ftplib.py line 503, in storbinary

### ISSUE THREAD

**Issue by mehargags** [olav-st/screencloud#341]
I just tried screencloud for the first time... and I'm getting this error when trying to upload screnshots to my FTP server.
Strangely... this error prevails on both my Windows and Linux machines.
`screencloud\python35.zip\ftplib.py line 503, in storbinary`

Detailed screenshot : https://prnt.sc/ms9ais

The FTP seems to be working absolutely fine otherwise through other clients.
Please share any fixes :)

**Comment by Nolram12345** [comment]
I experience the same issue. Please fix !

**Comment by rexjohannes** [comment]
i have the same problem

**Comment by rexjohannes** [comment]
[Screen](http://imgur.com/B1jpJ0Zl.png)
