### ISSUE TITLE
Rebind enter (feature request)

### ISSUE THREAD

**Issue by Zaliphyr** [olav-st/screencloud#342]
Ragnar wants me to move from snipping tool to screencloud, and i will gladly switch if i could rebind the enter to take a screenshot button to somthing closer to my hand as i dont want to move to the enter button.

If Ragnar asks..... tell him that hes wrong!

**Comment by olav-st** [comment]
Not possible to rebind it at the moment, but you can use `Ctrl+S` instead of `Enter`. Is that closer to your hand? ✋

**Comment by lizardion1** [comment]
That works great, would love a rebind later on tho
