### ISSUE TITLE
Black Screen on main screen but fine on the other...

### ISSUE THREAD

**Issue by ghost** [olav-st/screencloud#351]
So, weird issue eh, if both monitors are on the left is fine but main is black or messed up like shown in the pic or if i disable the other monitor my main is fine.... im using nvidia gpu, ubuntu 19.04

![image](https://user-images.githubusercontent.com/32229772/61833734-28c24780-ae6d-11e9-8997-8b4f50cf7992.png)

Im on 1.5.0.

**Comment by Chaottiic** [comment]
Similar issue happens on MacOS Catalina, just instead it is all black. 

Running MacBook Pro 2018 

Graphics -[
Radeon Pro 555X 4 GB
Intel UHD Graphics 630 1536 MB
]

Version of ScreenCloud is 1.5
