### ISSUE TITLE
Problème de démarrage

### ISSUE THREAD

**Issue by SevenSoulsss** [olav-st/screencloud#359]
deleted

**Comment by olav-st** [comment]
Any french speakers that can help out here?

**Comment by smaragdus** [comment]
@olav-st 

**machine translation:**

> Startup problem # 359
> 
> Since yesterday my ScreenCloud refuses to start, I tried to launch it as an administrator but still nothing, I restarted my pc but it still does not start, I uninstalled and reinstalled the software and still nothing, it comes from the software or me? Can you help me ?
