### ISSUE TITLE
Can't change filename of the screenshot while savng

### ISSUE THREAD

**Issue by Bandydan** [olav-st/screencloud#36]
For all the options (ScreenCloud, File, FTP, SFTP) editing filename is impossible. It can be cut, pasted, but does not allow input inside the text field.

OS: Ubuntu 12.04 LTS
I have set up screencloud from the repo.

**Comment by wolandtel** [comment]
Still actual for local file (for Windows, at least). File always being saved with name from settings.

**Comment by tonemackay** [comment]
I can confirm this problem still exists in version 1.3.0 running on Windows 10. 

Steps to reproduce:

1. Select **Save to**, then **Ask Me..** from the system tray.
2. Select **Capture Selection**.
3. Capture the selection then press **Enter**.
4. Save Screenshot dialog is loaded. Select **Local File**, give it a name and then click **OK**.
5. The screenshot is saved to the local folder using the name from the settings.
