### ISSUE TITLE
Open image in app

### ISSUE THREAD

**Issue by jeremycherfas** [olav-st/screencloud#360]
I would like an option to open an image in an image editor, so that I can obscure details when I need to.

Is that something that could be implemented in future?

**Comment by olav-st** [comment]
This is already implemented. Click on the thumbnail in the save dialog to edit. :)

**Comment by jeremycherfas** [comment]
OK; that's pretty cool and I confess I had not noticed the pencil icon. Thanks.

I still think it would be great if you added another tool that might add a lot of blur within the box, in case I need to send an image but do not want to share sensitive information.

Or maybe that is there too, and I just cannot see it. :)

Jeremy
