### ISSUE TITLE
ScreenCloud upload failed

### ISSUE THREAD

**Issue by YerkoPalma** [olav-st/screencloud#37]
![screenshot from 2014-01-30 19 36 44](https://f.cloud.github.com/assets/5105812/2045942/8941d17c-89ff-11e3-8c4b-25f27468bd72.png)

I have this problem... when ever I take a screenshot it can't be uploaded, I get this error... Any idea?

**Comment by olav-st** [comment]
Closing this since the screenshot hosting service has been shut down.
