### ISSUE TITLE
Capture selection freezes when application has been open for a while - Ubuntu 19.10

### ISSUE THREAD

**Issue by Metichi** [olav-st/screencloud#370]
I am using Screencloud 1.5.1 in an ubuntu 19.10 machine.

For a while now, whenever screencloud has been open for more than a few hours (can't tell the time exactly), trying to capture a region of the screen freezes the program and the whole display it's in.

It will show the grey overlay, and let me draw a square, but once the square is drawn, it's stuck on the overlay, and wont detect the intro or react in any way.
To go back to normal, I have to manage to kill the process, either in another monitor or by moving to another virtual desktop.

**Comment by Panda-ref** [comment]
Same here Screencloud 1.5.3 snap version.
Linux mint 20.1 Cinnamon
