### ISSUE TITLE
Questions on functionality

### ISSUE THREAD

**Issue by Yakabuff** [olav-st/screencloud#371]
1) Is it possible to save to 2 places at once. eg: save to clipboard and to local file at the same time

2) When using the area selector, take screenshot without having to press enter

**Comment by overlordqd** [comment]
I have just updated screencloud to newest version, and I've lost the ability to use multiple save locations.

I was saving to filesystem plus clipboard. Can you please fix this, or tell me which version supports this feature?

**Comment by Yakabuff** [comment]
> I have just updated screencloud to newest version.
>  tell me which version supports this feature?

the version you've just updated from probably supports this feature xD

**Comment by overlordqd** [comment]
> 
> 
> > I have just updated screencloud to newest version.
> > tell me which version supports this feature?
> 
> the version you've just updated from probably supports this feature xD

Sorry, @Yakabuff I've confused the apps I used. I thought I were using screencloud, but it was Lightscreen.

https://lightscreen.com.ar/
