### ISSUE TITLE
Add support for macOS Big Sur

### ISSUE THREAD

**Issue by gerbenp** [olav-st/screencloud#377]

**Comment by Waradmiraal** [comment]
I have the same problem

**Comment by KAVA-Leigh** [comment]
Had the same issue on Monterey, then found this issue still open, so that makes sense now.

**Comment by jvlobo** [comment]
Is there any news about this? I updated to Big Sur and now when I open ScreenCloud it just gets stuck and I have to force quit it :(

**Comment by theMikelProject** [comment]
Facing the exact same issue on an M1 Big Sue with the app just being stuck.

**Comment by netsurfer38** [comment]
A real shame to see that months on, the situation remains the same! It is one of the real frustrations with many an excellent free software program that all too often does not seem to have a dedicated team backing it. In the end it does free software no favours.

**Comment by olav-st** [comment]
Let's hope that someone who uses macOS Big Sur will do free software a favor and contribute a fix 😉
