### ISSUE TITLE
Screenshots select other screens in a multi-monitor setup.

### ISSUE THREAD

**Issue by ImWeax** [olav-st/screencloud#382]
I have 2 monitors, and before the most recent update, screenshotting worked normally. Post update, whenever i take a screenshot on my left monitor (monitor 2), it shows up as just black on the selection screen/ the screenshot. on the right screen (monitor 1) it shows the left monitors display. Have tried reinstalling and restarting, and restarting graphics drivers, with nothing fixing.

**Comment by ToxicMC** [comment]
I'm having the same issue on a 3 monitor setup (middle monitor is the main). If I try to take a screenshot on the left monitor, it shows up as a black screen, and if I try to take a screenshot on the middle, or right monitor, it will preview whatever is on the monitor to the left of it.

**Comment by tomasgeci** [comment]
I have the same issue. Two monitor setup. On main monitor screenshot capturing works well but on second monitor I get black screen. I updated to most recent version but I don't remember last working version.

Windows 10 home x64, same behavior with most recent versions of win10 updates.

**Comment by brezitsky** [comment]
Hi there, same issue. I have two monitors setup, layout is vertical.
![зображення](https://user-images.githubusercontent.com/10748198/102608886-47e10980-4133-11eb-901c-8c997878588f.png)

When I take a screenshot from main monitor everything is ok. But when on second it shows black screen. Or in some cases shows content from other monitor.

BUT. When I placed monitors in horizontal layout everything works fine.

**Comment by ImWeax** [comment]
It seems the issue happens when monitors are set in an order that isn't ascending. Program works as intended if they are set up like this.
![image](https://user-images.githubusercontent.com/59857479/102679435-03716e80-4204-11eb-9d61-a41e979afced.png)

My setup has them ordered 2,1 and This is when the issue occurs.
![image](https://user-images.githubusercontent.com/59857479/102679431-f8b6d980-4203-11eb-96af-144ddd106da6.png)

**Comment by hawk-niemetz** [comment]
My screens (laptop on left, 1, and monitor on right, 2) are set up in ascending order and I still have issues.

**Comment by InfiRandia** [comment]
I also have this issue, same display settings as @ImWeax. All versions above v1.5.1 is causing this issue. In v1.5.3, when I use "Capture section" while standing within Monitor 1, I get a snap picture of Monitor 2 on Monitor 1. Doing a "Capture Section" on Monitor 2 causes as others say above.. a black snap image when having only 2 monitors.

Downgrading to **v1.5.1**. it's the only version that works correctly right now on windows.

**Comment by tomasgeci** [comment]
@InfiRandia I can confirm that v1.5.1 works fine.

1.5.2 and 1.5.3 not.

**Comment by hawk-niemetz** [comment]
Confirmed 1.5.1 works as expected across 2 monitors.
Also I couldn't set custom shortcuts but in 151 that works (ie using the shortcuts = screengrab)

**Comment by Gwen22** [comment]
Hi,

Same problem here with 2 monitors and 1.5.3 version.

My screen 1 (mainscreen) before I press screenshot shortcut:
![screen1](https://user-images.githubusercontent.com/13748253/103437221-34e73280-4c25-11eb-8be0-0fa960a882b0.jpg)

After I pressed screenshot shortcut:
![screen2](https://user-images.githubusercontent.com/13748253/103437227-44667b80-4c25-11eb-9554-060019264e44.jpg)

My screens are like this:
![Screenshot at 11-22-32](https://user-images.githubusercontent.com/13748253/103437236-6b24b200-4c25-11eb-8b7d-7ed68d9c4381.png)

Screen 1 resolution : 3440 x 1440
Screen 2 : resolution 1080 x 1920

**Comment by hawk-niemetz** [comment]
> Screen 1 resolution : 3440 x 1440
> Screen 2 : resolution 1080 x 1920
> 
> Same problem with "Capture multiple monitors" activated or desactivated.
> 
> I installed 1.5.1 version and it works now.

Hey @Gwen22 

what happens when you use left/right keys to go from screen 1 to 2, and back to 1? 

When I do this I get a mis-sized overlay (it is sized as the opposite monitor...)

I have to start capture 2 times; first time = wrong overlay size; Cancel; second time overlay = correct

**Comment by Gwen22** [comment]
> > Screen 1 resolution : 3440 x 1440
> > Screen 2 : resolution 1080 x 1920
> > Same problem with "Capture multiple monitors" activated or desactivated.
> > I installed 1.5.1 version and it works now.
> 
> Hey @Gwen22
> 
> what happens when you use left/right keys to go from screen 1 to 2, and back to 1?
> 
> When I do this I get a mis-sized overlay (it is sized as the opposite monitor...)
> 
> I have to start capture 2 times; first time = wrong overlay size; Cancel; second time overlay = correct
> 
> ** this is using 1.5.1 ... ** (on Win10)

With 1.5.1 version, everything is ok when I use left/right keys to switch screen. No wrong overlay at all.

**Comment by Aleteh** [comment]
Im running 1.5.2 and i can still not use multiple monitors and capture a selection box. It just either greys out the other monitors or it moves all app windows to one monitor

**Comment by CvH** [comment]
Same for me, 1.5.1 at Win10 works, 1.5.2 and 1.5.3 does not work.

This is not just if you screwed up the monitor alignment, also if you mix different Monitor sizes you get very strange behavior.
![image](https://user-images.githubusercontent.com/1355173/112102025-ed2ed200-8ba7-11eb-9e4a-56c2fc63acdc.png)

If you screenshot a single monitor you loose parts of the screen
![image](https://user-images.githubusercontent.com/1355173/112101931-c5d80500-8ba7-11eb-8bf6-1bae2733607e.png)

if you do a screenshot of all monitors you get something like that that may be okay-ish
![image](https://user-images.githubusercontent.com/1355173/112102474-9aa1e580-8ba8-11eb-80f7-e1db51f69be0.png)


if your monitor alignment is that way it is basically unusable
![image](https://user-images.githubusercontent.com/1355173/112102681-ebb1d980-8ba8-11eb-9710-bbdd993ca136.png)

![image](https://user-images.githubusercontent.com/1355173/112102790-11d77980-8ba9-11eb-98d4-b717cf553c14.png)

**Comment by Gwen22** [comment]
Still have same problem. Annoying :/

**Comment by CvH** [comment]
dead project ?

**Comment by olav-st** [comment]
I'm not actively working on it but contributions are welcome!
