### ISSUE TITLE
Nextcloud Support

### ISSUE THREAD

**Issue by nisutec** [olav-st/screencloud#390]
Please add a Nextcloud Plugin to Screencloud. Nextcloud is a open source cloud solution that allows user to create easily his own cloud for data, videos and many other things. It would be great if Screencloud can get a Plugin for this that automatically sends the Screenshot to the Nextcloud and puts a share link in to the clipboard to easily share it.

**Comment by olav-st** [comment]
What about https://github.com/Section214/screencloud-owncloud ?

**Comment by temik4** [comment]
> What about https://github.com/Section214/screencloud-owncloud ?

I tried this solution. Unfortunately, it looks abandoned and is no longer being developed. I checked it and another fork. In both cases, I get a message about an incorrect URL, although how can you make a mistake...
