### ISSUE TITLE
[Improvement] Put the direct uploaded file path for premium accounts

### ISSUE THREAD

**Issue by raelgc** [olav-st/screencloud#47]
Hi @olav-st,

My main use of Screencloud is for capture my screen quickly and paste into developer chat tools, like Atlassian Hipchat or Campfire (Snakefire client on Ubuntu).

These chats always get the URL, and it contains an image file, the image is automatically rendered for the team into that chat.

But, as Screencloud, after upload the image, give me an indirect URL, I have to open the URL in the browser, then click into the image, then copy the URL to paste into other places.

My proposal is: for premium accounts, give the option (into Settings) to return the direct URL path to the uploaded image.

**Comment by olav-st** [comment]
Closing this since the screenshot hosting service has been shut down.
