### ISSUE TITLE
Multiple displays on OS X

### ISSUE THREAD

**Issue by BirknerAlex** [olav-st/screencloud#70]
Hi Olav,

sorry for the next report :) 

If I try to make a Screenshot of my second Display it will not work. On "Capture Full Screen" I got an screenshot of the first Display.
On "Capture Selection" it shows up the first Display on the second one.

Its not a important bug. For the quick solution I move the window to the main / first Display and took the screenshot.

Best regards,
Alexander

**Comment by SerDIDG** [comment]
Some problem with grey screen on second monitor too, Macbook Air '11 711b, Yosemite.

**Comment by pcollaog** [comment]
Same issue in El Capitan Beta4

**Comment by dawidk92** [comment]
Fix it ;_____;
