### ISSUE TITLE
Capture Selection doesn't work on OSX 10.8.5

### ISSUE THREAD

**Issue by wdamien** [olav-st/screencloud#75]
Using v1.1.6, clicking "Capture Selection" or using the keyboard shortcut doesn't do anything. No errors, just nothing happens.

System Details:
OSX 10.8.5
2.6 Ghz Intel Core i7
8 GB memory

**Comment by llybin** [comment]
@wdamien, @1ricca can you check last version?

**Comment by wdamien** [comment]
@llybin Version 1.2 works for me now, using OSX 10.9.5.  Thanks!
