### ISSUE TITLE
I can't even install it.

### ISSUE THREAD

**Issue by mykola-adbeat** [olav-st/screencloud#8]
Linux 3.8.0-31-generic #46-Ubuntu SMP Tue Sep 10 19:56:49 UTC 2013 i686 i686 i686 GNU/Linux

$ sudo dpkg -i screencloud_1.1.2_i386.deb 
Selecting previously unselected package screencloud.
(Reading database ... 469053 files and directories currently installed.)
Unpacking screencloud (from screencloud_1.1.2_i386.deb) ...
dpkg: dependency problems prevent configuration of screencloud:
 screencloud depends on libqtsingleapplication; however:
  Package libqtsingleapplication is not installed.
 screencloud depends on libqxt-gui0; however:
  Package libqxt-gui0 is not installed.
 screencloud depends on libquazip0; however:
  Package libquazip0 is not installed.
 screencloud depends on libqtscript4-qtbindings; however:
  Package libqtscript4-qtbindings is not installed.

dpkg: error processing screencloud (--install):
 dependency problems - leaving unconfigured
Processing triggers for hicolor-icon-theme ...
Processing triggers for bamfdaemon ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for desktop-file-utils ...
Processing triggers for gnome-menus ...
Errors were encountered while processing:
 screencloud

Can't figure out where libqtsingleapplication should be in repos.
Next question is how to delete an account? Even video on the home page doesn't play.

**Comment by erama** [comment]
Hi Olav, I try to install in Lubuntu 14.10 but I don't have libquazip0 I have libquazip1 .. how can I do install it? I need recompile the packed?

Thanks

**Comment by olav-st** [comment]
Have you tried the 14.10 package from here? http://software.opensuse.org/download.html?project=home%3Aolav-st&package=screencloud

If it dosen't work you could try compiling it yourself of course, see https://github.com/olav-st/screencloud/wiki/Compiling-on-Ubuntu
