### ISSUE TITLE
Capture selection not working in Arch Linux

### ISSUE THREAD

**Issue by rjbrooksjr** [olav-st/screencloud#80]
I have 1.1.6 installed on two different PCs with updated Arch Linux. On both I can capture full screen and active window just fine, but nothing happens when i press alt+shift+2 for a selection capture.

**Comment by antoniy** [comment]
I'm having this issue as well. I'm running Arch on two monitors and I'm using version 1.1.6-2 from AUR. I see this issue takes a while to address. What's the status currently?

**Comment by subdigger** [comment]
same for me. no popup appears on shortcats.
is there place to change key combination ?
