### ISSUE TITLE
Hotkeys not working

### ISSUE THREAD

**Issue by ashtreylil** [olav-st/screencloud#82]
title says it. hotkeys are nonfuntional even using hotkeys i know have no conflict like "ctrl+alt+<"

ubuntu 14.04

**Comment by olav-st** [comment]
Any output if you run it from the terminal?

**Comment by solvek** [comment]
Hello
I have upgraded ubuntu to 16.04 and hotkeys stopped to work for me.

I have no output in terminal.

It seems that for some reason hot key works if Screencloud is active (for example preferences window) but does not work globally.

**Comment by rtyshyk** [comment]
I've the some issue. ubuntu 16.04, screencloud 1.3.0 for repo

**Comment by xepybumka** [comment]
I've the some issue. Ubuntu 22.04. Tryed to change hotkeys but... It doesn't work.
Screencloud 1.5.3
