### ISSUE TITLE
[Windows] assign PtrScn button on keyboard as a hotkey

### ISSUE THREAD

**Issue by greg-witczak** [olav-st/screencloud#84]
I'd like to assign `PrtScn` button on my keyboard as a ScreenCloud hotkey for capturing selection - but I'm unable to do that. When I have "Press a key combination..." text, pressing this key does nothing.

Is it related to my keyboard or OS (Windows 8.1)? I'm using ScreenCloud 1.1.6.

**Comment by canda** [comment]
+1

**Comment by wolandtel** [comment]
+1

**Comment by e-M-c-E** [comment]
+100 for that option :)
Confirmed: win seven x64, screen cloud 1.2.0
