### ISSUE TITLE
Capture Window Border problems

### ISSUE THREAD

**Issue by goosewoman** [olav-st/screencloud#86]
capture window border is capturing a bit too much of the screen.
In maximized windows you see part of the taskbar and there's a big black border around the screenshot. ex: ![Image of example 1](http://i.imgur.com/6R5ez90.png) ![Image of example 2](http://i.imgur.com/UKnPx7K.png)

And in smaller widnows you see a row of pixels outside of the border on the right and bottom side. ex: ![Image of example 3](http://i.imgur.com/WiCIBf1.png)

using screencloud version 1.1.6 and windows 8 professional 64 bit

**Comment by ghprod** [comment]
any update for this?

i'm using on Freya based on Ubuntu, but i cant include window border :(

**Comment by Trucido** [comment]
This bug is present on Windows 10 but I don't recall it being an issue on Windows 8. @kukelekuuk00 did you modify window border size at all using TinyWindowBorders.exe or WinaeroTweaker?
