### ISSUE TITLE
OS X – Unable to parse RSA private key

### ISSUE THREAD

**Issue by jwflory** [olav-st/screencloud#89]
I recently installed ScreenCloud to my OS X iMac running 10.9.4.

I use RSA key authentication on my private server, which I planned to use with ScreenCloud. However, whenever I add my RSA private key from `~/.ssh/id_rsa` and attempt to upload a screenshot, ScreenCloud is unable to parse my RSA private key. See screenshot below:
![f7985f7a51edaa5c8f260dab7406c1ed](https://cloud.githubusercontent.com/assets/4721034/3529453/bc2f58d0-0799-11e4-8bd2-f8094d097ae0.png)
Alternatively, I have tried converting my RSA key to a .txt and .key file, but that had no effect. I'm not sure how I can get ScreenCloud to recognize my RSA private key.

Any help would be appreciated. Thanks.

**Comment by ElijahLynn** [comment]
I am also getting "unbable to parse key file", on Ubuntu 14.04 and SC 1.1.6. I will try some of the above recommendations.

**Comment by ElijahLynn** [comment]
Okay, the issue was that my keyfile has a passphrase and I just haven't used it in so long I forgot about it. Converting to the PEM file requires a passphrase and then strips out the passphrase. So just set the passphrase in the SC settings and it connects then.

**Comment by ElijahLynn** [comment]
The error message could be improved a bit. If possible to determine if it is a bad passphrase then reflect that in the error message instead of the parse error but if not then just say "unable to parse key file OR bad passphrase".

**Comment by ElijahLynn** [comment]
bot: still an issue I believe.
