### ISSUE TITLE
OSX Compilation Doc

### ISSUE THREAD

**Issue by aarnrvera** [olav-st/screencloud#93]
Is this a priority? Would love to build this on OSX.

**Comment by olav-st** [comment]
I'll try to do a writeup when I compile the Qt 5 version on OS X :)

**Comment by olav-st** [comment]
Here's a quick writeup: https://github.com/olav-st/screencloud/wiki/Compiling-on-Mac-OS-X
Please let me know if you run into problems.

**Comment by nmoya** [comment]
Hey @olav-st. Thank you very much for your writeup. Unfortunately, I ran into some problems.
The very last bit of it, the make command to build screencloud itself: http://screencloud.net/v/8PVx

I set the -std compiler flag to c++11 in case it was a problem of language standard. The errors changed, but they still occur.
Apparently all the other steps worked, do you have any ideia if I need to set a specific flag, change compiler, versions, etc that could be causing this?

**Comment by olav-st** [comment]
Some quick googling suggests that the errors you're getting might be related to the `pyport.h` patch. There seems to be a workaround available: https://trac.macports.org/ticket/44288. Let me know if it works and I'll add it to the wiki :smile:

**Comment by nmoya** [comment]
That worked. I have two "pyport.h" in my computer:
1) `/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7/pyport.h`
2) `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7/pyport.h`

I had patched only number 2 before writting the issue, I repeated the processed described in your writeup for the pyport at location 1 and it worked. Thanks a lot man!
