### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by ghost** [olav-st/screencloud#94]
I have an Arch Linux with MATE desktop. However, I don't like notifications from tray and I think it would be wonderful, if notifications would have a notification from DE in the top right corner. For example, here is the Guake's one: https://i.imgur.com/hwErBZA.png . Sorry for my bad english, though, it's not my native lang.

**Comment by Beanow** [comment]
:+1: would love to see this too.
This kind of notification is provided by the Notify OSD package and it provides both an API for most languages as well as the `notify-send` executable.
