### ISSUE TITLE
[Windows 8] Name of the image won't go above 9 

### ISSUE THREAD

**Issue by punihassteuch** [olav-st/screencloud#96]
Hi! 

First: i love screencloud, its so simple! Thanks!

But there are some little problems, i have windows 8, and upload the images direct to my webspace, that works fine, but when i use the code {rnd} as a name, the number won't go above 9, and screencloud replaces some screens, actually i'm using {rnd_h}, but the hash is really really long.

like this: http://img.********.eu/46072e0d4538e15849f1b0b8b9753399.jpg

is there any plugin that shorts the url or a way to get more numbers? 

regards.

**Comment by olav-st** [comment]
See https://github.com/olav-st/screencloud/issues/10. I'm planning to improve {rnd}.
